import { Injectable, Logger } from '@nestjs/common';
import * as https from 'https';
import { RedisService } from '../redis/redis.service';
import { QwenAuthManager } from './auth/qwen-auth.manager';
import { DeepSeekAuthManager } from './auth/deepseek-auth.manager';
import { DeepSeekPowSolver } from './pow/deepseek-pow.solver';
import { FreeAiSseParser } from './sse/free-ai-sse.parser';

export type FreeAiProvider = 'qwen' | 'deepseek';

export interface FreeAiChatRequest {
  provider: FreeAiProvider;
  model?: string;
  prompt: string;
  systemPrompt?: string;
  temperature?: number;
  thinkingMode?: boolean;
}

export interface FreeAiChatResponse {
  thinking: string;
  answer: string;
  provider: FreeAiProvider;
  model: string;
  cached: boolean;
}

const CACHE_PREFIX = 'free-ai:response:';
const CACHE_TTL = 90 * 1000; // 90 seconds in ms

@Injectable()
export class FreeAiService {
  private readonly logger = new Logger(FreeAiService.name);
  private lastRequestTime: Record<FreeAiProvider, number> = { qwen: 0, deepseek: 0 };
  private readonly MIN_INTERVAL_MS = 5000;

  constructor(
    private readonly redis: RedisService,
    private readonly qwenAuth: QwenAuthManager,
    private readonly deepSeekAuth: DeepSeekAuthManager,
    private readonly powSolver: DeepSeekPowSolver,
    private readonly sseParser: FreeAiSseParser,
  ) {}

  async chat(req: FreeAiChatRequest): Promise<FreeAiChatResponse> {
    const cacheKey = `${CACHE_PREFIX}${req.provider}:${this.hashPrompt(req.prompt)}`;
    const cached = await this.redis.get(cacheKey);
    if (cached) {
      this.logger.debug(`Free AI cache hit for provider=${req.provider}`);
      return { ...(cached as any), cached: true };
    }

    await this.enforceRateLimit(req.provider);

    let result!: FreeAiChatResponse;
    let retries = 0;
    while (retries <= 2) {
      try {
        result = req.provider === 'qwen'
          ? await this.chatQwen(req)
          : await this.chatDeepSeek(req);
        break;
      } catch (err: any) {
        this.logger.warn(`Free AI ${req.provider} attempt ${retries + 1} failed: ${err.message}`);
        if (retries === 2) throw err;
        if (err.message?.includes('401') || err.message?.includes('403')) {
          if (req.provider === 'qwen') await this.qwenAuth.refreshToken();
          else await this.deepSeekAuth.refreshSession();
        }
        retries++;
      }
    }

    await this.redis.set(cacheKey, result, CACHE_TTL);
    return { ...result, cached: false };
  }

  private async chatQwen(req: FreeAiChatRequest): Promise<FreeAiChatResponse> {
    const token = await this.qwenAuth.getToken();
    const model = req.model || 'qwen-max';
    const thinkingMode = req.thinkingMode ?? (process.env.FREE_AI_QWEN_THINKING === 'true');

    const body = JSON.stringify({
      model,
      messages: [
        ...(req.systemPrompt ? [{ role: 'system', content: req.systemPrompt }] : []),
        { role: 'user', content: req.prompt },
      ],
      stream: true,
      temperature: req.temperature ?? 0.2,
      ...(thinkingMode ? { enable_thinking: true } : {}),
    });

    const rawLines = await this.makeStreamRequest(
      'chat.qwen.ai', '/api/chat/completions', 'POST',
      { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
      body,
    );

    const result = this.sseParser.accumulateQwenStream(rawLines);
    return { ...result, provider: 'qwen', model, cached: false };
  }

  private async chatDeepSeek(req: FreeAiChatRequest): Promise<FreeAiChatResponse> {
    const session = await this.deepSeekAuth.getSession();
    const model = req.model || 'deepseek-reasoner';

    // Step 1: Create chat session to get chat_session_id
    const sessionRes = await this.makeJsonRequest(
      'chat.deepseek.com', '/api/v0/chat_session/create', 'POST',
      this.buildDeepSeekHeaders(session.token, session.cookies),
      JSON.stringify({ character_id: null }),
    );
    const chatSessionId = sessionRes?.data?.biz_data?.id;
    if (!chatSessionId) {
      throw new Error(`Failed to create DeepSeek chat session: ${JSON.stringify(sessionRes)}`);
    }

    // Step 2: Get PoW challenge
    const challengeRes = await this.makeJsonRequest(
      'chat.deepseek.com', '/api/v0/chat/create_pow_challenge', 'POST',
      this.buildDeepSeekHeaders(session.token, session.cookies),
      JSON.stringify({ target_path: '/api/v0/chat/completion' }),
    );

    const challengeObj = challengeRes?.data?.biz_data?.challenge || challengeRes?.data?.challenge;
    if (!challengeObj) {
      throw new Error(`PoW challenge not generated by DeepSeek API: ${JSON.stringify(challengeRes)}`);
    }

    const powHeader = this.powSolver.solve(
      challengeObj.challenge,
      challengeObj.salt,
      challengeObj.difficulty,
      challengeObj.expire_at,
      challengeObj.signature,
      challengeObj.target_path,
    );

    // Step 3: Stream completion using proprietary web client body format
    const thinkingMode = req.thinkingMode ?? (process.env.FREE_AI_DEEPSEEK_THINKING === 'true');
    const fullPrompt = req.systemPrompt ? `${req.systemPrompt}\n\n${req.prompt}` : req.prompt;
    const body = JSON.stringify({
      chat_session_id: chatSessionId,
      parent_message_id: null,
      prompt: fullPrompt,
      ref_file_ids: [],
      thinking_enabled: thinkingMode,
    });

    const headers = {
      ...this.buildDeepSeekHeaders(session.token, session.cookies),
      'Content-Type': 'application/json',
      'X-DS-PoW-Response': powHeader,
    };

    const rawLines = await this.makeStreamRequest(
      'chat.deepseek.com', '/api/v0/chat/completion', 'POST', headers, body,
    );

    const result = this.sseParser.accumulateDeepSeekStream(rawLines);
    return { ...result, provider: 'deepseek', model, cached: false };
  }

  private makeStreamRequest(
    hostname: string, path: string, method: string,
    headers: Record<string, string>, body: string,
  ): Promise<string[]> {
    return new Promise((resolve, reject) => {
      const lines: string[] = [];
      const req = https.request({
        hostname, path, method,
        headers: { ...headers, 'Content-Length': Buffer.byteLength(body) }
      }, (res) => {
        if (res.statusCode && res.statusCode !== 200) {
          reject(new Error(`Request failed with status code ${res.statusCode}`));
          return;
        }
        let buffer = '';
        res.on('data', (chunk: Buffer) => {
          buffer += chunk.toString();
          const parts = buffer.split('\n');
          buffer = parts.pop() || '';
          for (const part of parts) { if (part.trim()) lines.push(part.trim()); }
        });
        res.on('end', () => resolve(lines));
        res.on('error', reject);
      });
      req.on('error', reject);
      req.write(body);
      req.end();
    });
  }

  private makeJsonRequest(
    hostname: string, path: string, method: string,
    headers: Record<string, string>, body: string,
  ): Promise<any> {
    return new Promise((resolve, reject) => {
      const req = https.request({
        hostname, path, method,
        headers: { ...headers, 'Content-Length': Buffer.byteLength(body) }
      }, (res) => {
        let data = '';
        res.on('data', (chunk: Buffer) => { data += chunk.toString(); });
        res.on('end', () => { try { resolve(JSON.parse(data)); } catch (e) { reject(e); } });
        res.on('error', reject);
      });
      req.on('error', reject);
      req.write(body);
      req.end();
    });
  }

  private buildDeepSeekHeaders(token: string, cookies: Record<string, string>): Record<string, string> {
    const cookieStr = Object.entries(cookies).map(([k, v]) => `${k}=${v}`).join('; ');
    return {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Cookie': cookieStr,
      'Origin': 'https://chat.deepseek.com',
      'Referer': 'https://chat.deepseek.com/',
    };
  }

  private async enforceRateLimit(provider: FreeAiProvider): Promise<void> {
    const elapsed = Date.now() - this.lastRequestTime[provider];
    if (elapsed < this.MIN_INTERVAL_MS) {
      await new Promise(r => setTimeout(r, this.MIN_INTERVAL_MS - elapsed));
    }
    this.lastRequestTime[provider] = Date.now();
  }

  private hashPrompt(prompt: string): string {
    const { createHash } = require('crypto');
    return createHash('md5').update(prompt).digest('hex').slice(0, 16);
  }

  /** Convenience for llm_filter node: returns 'LONG' | 'SHORT' | 'FILTER' */
  async filterSignal(
    provider: FreeAiProvider,
    model: string,
    systemPrompt: string,
    marketContext: string,
    temperature = 0.2,
  ): Promise<'LONG' | 'SHORT' | 'FILTER'> {
    const res = await this.chat({ provider, model, prompt: marketContext, systemPrompt, temperature });
    const answer = res.answer.toUpperCase();
    if (answer.includes('LONG')) return 'LONG';
    if (answer.includes('SHORT')) return 'SHORT';
    return 'FILTER';
  }

  /** AI Copilot to generate or modify ReactFlow strategy graphs */
  async generateCopilotStrategy(req: {
    provider?: FreeAiProvider;
    prompt: string;
    currentNodes?: any[];
    currentEdges?: any[];
    pair?: string;
    timeframe?: string;
  }): Promise<{ thinking: string; strategy: any; rawAnswer: string }> {
    const provider = req.provider || 'qwen';
    const pair = req.pair || 'BTCUSDT';
    const timeframe = req.timeframe || '15m';

    const systemPrompt = `You are a professional trading strategy constructor for the Cyber-Quant bot.
Your task is to generate or modify a valid visual trading strategy graph that complies with ReactFlow structure.

The strategy MUST end in a single "signal" node (type: "signal").
The available node types are:
1. "exchange": Price/market data source.
   - data: { mode: "ticker" | "scanner", dataType: "price" | "funding_rate", pair: "${pair}" }
2. "indicator": Technical indicator.
   - data: { name: "RSI" | "SMA" | "EMA" | "MACD" | "Volume", params: { period: number } (for MACD: { fast: 12, slow: 26, signal: 9 }), timeframe: "${timeframe}" }
3. "comparison": Evaluates math comparison between left (handle "a") and right (handle "b").
   - data: { operator: ">" | "<", aValue: number (fallback if handle "a" empty), bValue: number or "value" (fallback if handle "b" empty) }
4. "cross": Evaluates crossover. Left (handle "a") crosses above/below right (handle "b").
   - data: { direction: "above" | "below", aValue: number, bValue: number }
5. "logic": Combines inputs.
   - data: { operator: "AND" | "OR" | "NOT" }
6. "timeFilter": Restricts execution hours.
   - data: { from: "08:00", to: "22:00", timezone: "UTC" }
7. "llm_filter": AI filter node that sits before the signal node.
   - data: { provider: "qwen" | "deepseek", model: "qwen-max" | "deepseek-reasoner", promptTemplate: "template string", temperature: 0.2, mockBacktest: true }
8. "signal": The final output node (mandatory sink).
   - data: { signalType: "LONG" | "SHORT" | "NEUTRAL" }

Edges connect outputs to inputs. IMPORTANT rules for edges:
- Output of "exchange" goes to input of "indicator".
- Output of "indicator" goes to handle "a" (targetHandle: "a") of "comparison" or "cross".
- Comparison thresholds/values can be input edges to handle "b" (targetHandle: "b") or hardcoded as "bValue" / "value" in comparison data.
- Output of "comparison" / "cross" / "timeFilter" goes to "logic" or "llm_filter" or "signal".
- Output of "logic" goes to "llm_filter" or "signal".
- If "llm_filter" is used, it should receive the main logic flow as its input, and its output should connect to the final "signal" node.

Position nodes logically from left to right:
- Source nodes (exchange) at x: 100.
- Indicators at x: 400.
- Comparisons/crosses at x: 700.
- Logic / LLM filters at x: 1000.
- Signal node (root/sink) at x: 1300.

If currentNodes and currentEdges are provided, modify them according to the user's request. Otherwise, generate a new strategy from scratch.

You MUST reply with:
1. Short explanations of the strategy logic in Russian.
2. A JSON code block containing the visual strategy. Format:
\`\`\`json
{
  "name": "Название стратегии",
  "description": "Описание на русском",
  "nodes": [...],
  "edges": [...]
}
\`\`\`
Return valid JSON structure ONLY in the markdown code block. Do not miss connections. Ensure every node has unique IDs (e.g. node_1, node_2).`;

    let prompt = `User Request: ${req.prompt}\n`;
    if (req.currentNodes && req.currentNodes.length > 0) {
      prompt += `Current Strategy Nodes:\n${JSON.stringify(req.currentNodes, null, 2)}\n\n`;
      prompt += `Current Strategy Edges:\n${JSON.stringify(req.currentEdges, null, 2)}\n`;
    }

    let thinking = '';
    let strategy: any = null;
    let rawAnswer = '';

    try {
      const response = await this.chat({
        provider,
        prompt,
        systemPrompt,
        temperature: 0.2,
        thinkingMode: true,
      });

      thinking = response.thinking || '';
      rawAnswer = response.answer || '';

      // Parse JSON out of response.answer
      try {
        const match = response.answer.match(/```json([\s\S]*?)```/);
        const jsonStr = match ? match[1].trim() : response.answer.trim();
        strategy = JSON.parse(jsonStr);
      } catch (err) {
        this.logger.error(`Failed to parse strategy JSON from AI response: ${err.message}`);
        this.logger.error(`Raw AI response answer: ${response.answer}`);
        // Fallback: try to find any JSON-like substring
        try {
          const start = response.answer.indexOf('{');
          const end = response.answer.lastIndexOf('}');
          if (start !== -1 && end !== -1) {
            strategy = JSON.parse(response.answer.slice(start, end + 1));
          }
        } catch (err2) {
          this.logger.error(`Fallback JSON parsing failed: ${err2.message}`);
        }
      }
    } catch (chatError: any) {
      this.logger.error(`Free AI chat error: ${chatError.message}. Initiating auth refresh and deterministic fallback...`);
      // Force refresh on next execution attempt
      try {
        if (provider === 'qwen') {
          await this.qwenAuth.refreshToken();
        } else {
          await this.deepSeekAuth.refreshSession();
        }
      } catch (refreshErr: any) {
        this.logger.error(`Failed to force refresh auth: ${refreshErr.message}`);
      }
    }

    if (!strategy) {
      this.logger.warn(`AI Strategy Generation failed or timed out. Providing dynamic fallback strategy matching prompt.`);
      const promptLower = req.prompt.toLowerCase();
      
      if (promptLower.includes('macd')) {
        thinking = 'Поскольку AI провайдер временно недоступен, была сгенерирована стандартная стратегия MACD Crossover с использованием встроенных правил.';
        strategy = {
          name: "MACD Crossover",
          description: "Стратегия на базе пересечения MACD и сигнальной линии (Резервный генератор)",
          nodes: [
            {
              id: "node_exch",
              type: "exchange",
              position: { x: 100, y: 200 },
              data: { mode: "ticker", dataType: "price", pair }
            },
            {
              id: "node_macd",
              type: "indicator",
              position: { x: 400, y: 200 },
              data: { name: "MACD", params: { fast: 12, slow: 26, signal: 9 }, timeframe }
            },
            {
              id: "node_compare",
              type: "comparison",
              position: { x: 700, y: 200 },
              data: { operator: ">", aValue: 0, bValue: 0 }
            },
            {
              id: "node_signal",
              type: "signal",
              position: { x: 1000, y: 200 },
              data: { signalType: "LONG" }
            }
          ],
          edges: [
            { id: "e1", source: "node_exch", target: "node_macd" },
            { id: "e2", source: "node_macd", target: "node_compare", targetHandle: "a" },
            { id: "e3", source: "node_compare", target: "node_signal" }
          ]
        };
        rawAnswer = `### MACD Crossover Strategy\n${thinking}\n\n\`\`\`json\n${JSON.stringify(strategy, null, 2)}\n\`\`\``;
      } else if (promptLower.includes('ema') || promptLower.includes('sma') || promptLower.includes('ma') || promptLower.includes('cross') || promptLower.includes('пересеч')) {
        thinking = 'Поскольку AI провайдер временно недоступен, была сгенерирована стандартная стратегия скользящих средних MA Crossover.';
        strategy = {
          name: "MA Crossover",
          description: "Пересечение быстрой SMA 9 и медленной SMA 21 (Резервный генератор)",
          nodes: [
            {
              id: "node_exch",
              type: "exchange",
              position: { x: 100, y: 200 },
              data: { mode: "ticker", dataType: "price", pair }
            },
            {
              id: "node_sma_fast",
              type: "indicator",
              position: { x: 400, y: 150 },
              data: { name: "SMA", params: { period: 9 }, timeframe }
            },
            {
              id: "node_sma_slow",
              type: "indicator",
              position: { x: 400, y: 300 },
              data: { name: "SMA", params: { period: 21 }, timeframe }
            },
            {
              id: "node_cross",
              type: "cross",
              position: { x: 700, y: 200 },
              data: { direction: "above", aValue: 0, bValue: 0 }
            },
            {
              id: "node_signal",
              type: "signal",
              position: { x: 1000, y: 200 },
              data: { signalType: "LONG" }
            }
          ],
          edges: [
            { id: "e1", source: "node_exch", target: "node_sma_fast" },
            { id: "e2", source: "node_exch", target: "node_sma_slow" },
            { id: "e3", source: "node_sma_fast", target: "node_cross", targetHandle: "a" },
            { id: "e4", source: "node_sma_slow", target: "node_cross", targetHandle: "b" },
            { id: "e5", source: "node_cross", target: "node_signal" }
          ]
        };
        rawAnswer = `### MA Crossover Strategy\n${thinking}\n\n\`\`\`json\n${JSON.stringify(strategy, null, 2)}\n\`\`\``;
      } else {
        // RSI (Default)
        thinking = 'Поскольку AI провайдер временно недоступен, была сгенерирована стандартная стратегия RSI (RSI < 30) для входа в Long.';
        strategy = {
          name: "RSI Strategy",
          description: "Вход в лонг при опускании RSI ниже уровня перепроданности 30 (Резервный генератор)",
          nodes: [
            {
              id: "node_exch",
              type: "exchange",
              position: { x: 100, y: 200 },
              data: { mode: "ticker", dataType: "price", pair }
            },
            {
              id: "node_rsi",
              type: "indicator",
              position: { x: 400, y: 200 },
              data: { name: "RSI", params: { period: 14 }, timeframe }
            },
            {
              id: "node_compare",
              type: "comparison",
              position: { x: 700, y: 200 },
              data: { operator: "<", aValue: 30, bValue: 30 }
            },
            {
              id: "node_signal",
              type: "signal",
              position: { x: 1000, y: 200 },
              data: { signalType: "LONG" }
            }
          ],
          edges: [
            { id: "e1", source: "node_exch", target: "node_rsi" },
            { id: "e2", source: "node_rsi", target: "node_compare", targetHandle: "a" },
            { id: "e3", source: "node_compare", target: "node_signal" }
          ]
        };
        rawAnswer = `### RSI Strategy\n${thinking}\n\n\`\`\`json\n${JSON.stringify(strategy, null, 2)}\n\`\`\``;
      }
    }

    return {
      thinking,
      strategy,
      rawAnswer,
    };
  }
}
