"""
Signal Bot - Generated by Signal Bot Constructor
Bot Name: {{BOT_NAME}}
Generated: {{GENERATED_AT}}

Usage:
  1. Copy .env.example to .env and fill in your credentials
  2. Run: docker-compose up -d
"""

import asyncio
import os
import logging
from datetime import datetime
from dotenv import load_dotenv
from binance import AsyncClient, BinanceSocketManager
from telegram import Bot
from telegram.constants import ParseMode

from strategy import evaluate_strategy
from indicators import get_candles

load_dotenv()

# ─── Configuration ────────────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID   = os.environ.get("TELEGRAM_CHAT_ID", "")
BINANCE_API_KEY    = os.environ.get("BINANCE_API_KEY", "")
BINANCE_SECRET     = os.environ.get("BINANCE_SECRET", "")
TRADING_PAIRS      = [p.strip() for p in os.environ.get("TRADING_PAIRS", "BTCUSDT").split(",")]
SCAN_MODE          = os.environ.get("SCAN_MODE", "FIXED").upper() # "FIXED" or "GLOBAL"
GLOBAL_MIN_VOLUME  = float(os.environ.get("GLOBAL_MIN_VOLUME", "50000000")) # 50M USDT
GLOBAL_MAX_PAIRS   = int(os.environ.get("GLOBAL_MAX_PAIRS", "20"))
TIMEFRAME          = os.environ.get("TIMEFRAME", "15m")
CHECK_INTERVAL     = int(os.environ.get("CHECK_INTERVAL", "30"))
BOT_NAME           = os.environ.get("BOT_NAME", "Signal Bot")

def check_config():
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        return False, "❌ TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID is missing"
    if not BINANCE_API_KEY or not BINANCE_SECRET:
        return False, "❌ BINANCE_API_KEY or BINANCE_SECRET is missing"
    return True, ""

# ─── Logger ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

# ─── State (deduplication) ────────────────────────────────────────────────────
last_signal: dict[str, tuple[str, datetime]] = {}


def should_send(pair: str, signal_type: str, cooldown_minutes: int = 60) -> bool:
    """Prevent duplicate signals within cooldown window."""
    key = pair
    if key in last_signal:
        prev_type, prev_time = last_signal[key]
        elapsed = (datetime.utcnow() - prev_time).total_seconds() / 60
        if prev_type == signal_type and elapsed < cooldown_minutes:
            return False
    last_signal[key] = (signal_type, datetime.utcnow())
    return True


async def send_telegram_signal(bot: Bot, pair: str, signal_type: str, price: float, strategy_name: str):
    """Format and send a signal message to Telegram."""
    emoji = "🟢" if signal_type == "LONG" else "🔴"
    arrow = "🚀" if signal_type == "LONG" else "📉"

    text = (
        f"{arrow} *{signal_type} SIGNAL*\n"
        f"━━━━━━━━━━━━━━━━━━\n"
        f"💎 *Pair:* `{pair}`\n"
        f"💰 *Price:* `${price:,.4f}`\n"
        f"⏱ *Timeframe:* `{TIMEFRAME}`\n"
        f"📋 *Strategy:* `{strategy_name}`\n"
        f"🕐 *Time:* `{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}`\n"
        f"━━━━━━━━━━━━━━━━━━\n"
        f"_{BOT_NAME}_"
    )

    await bot.send_message(
        chat_id=TELEGRAM_CHAT_ID,
        text=text,
        parse_mode=ParseMode.MARKDOWN,
    )
    logger.info(f"Signal sent: {signal_type} {pair} @ {price}")


async def process_pair(client: AsyncClient, bot: Bot, pair: str, tickers: dict):
    """Fetch candles for one pair and evaluate strategy."""
    try:
        symbol = pair.replace('/', '').upper()
        candles = await get_candles(client, pair, TIMEFRAME)
        if not candles or len(candles) < 50:
            return

        # Pass tickers and current symbol for scanner logic
        result = await evaluate_strategy(candles, tickers=tickers, symbol=symbol, client=client)
        if result is None:
            return

        signal_type, current_price = result
        if not should_send(pair, signal_type):
            logger.debug(f"Duplicate suppressed: {signal_type} {pair}")
            return

        await send_telegram_signal(bot, pair, signal_type, current_price, "{{STRATEGY_NAME}}")

    except Exception as e:
        logger.error(f"Error processing {pair}: {e}")


async def main():
    """Main bot loop."""
    logger.info(f"Starting {BOT_NAME}...")
    
    ok, err = check_config()
    if not ok:
        logger.error(err)
        logger.info("Please configure the bot via Web UI (http://localhost:8080) and restart.")
        return

    logger.info(f"Monitoring {len(TRADING_PAIRS)} pairs on {TIMEFRAME}: {', '.join(TRADING_PAIRS)}")

    client = await AsyncClient.create(BINANCE_API_KEY, BINANCE_SECRET)
    bot = Bot(token=TELEGRAM_BOT_TOKEN)

    # Send startup notification
    try:
        await bot.send_message(
            chat_id=TELEGRAM_CHAT_ID,
            text=f"✅ *{BOT_NAME}* started\n"
                 f"📊 Pairs: {', '.join(TRADING_PAIRS)}\n"
                 f"⏱ Timeframe: {TIMEFRAME}",
            parse_mode=ParseMode.MARKDOWN,
        )
    except Exception as e:
        logger.warning(f"Could not send startup message: {e}")

    try:
        while True:
            # 1. Determine pairs to scan
            current_pairs = []
            tickers = {}
            
            try:
                raw_tickers = await client.futures_ticker()
                for t in raw_tickers:
                    symbol = t['symbol']
                    vol = float(t.get('quoteVolume', 0))
                    change = float(t.get('priceChangePercent', 0))
                    tickers[symbol] = { 'volume': vol, 'priceChangePercent': change }
                
                if SCAN_MODE == "GLOBAL":
                    # Filter only USDT perpetuals with high volume
                    eligible = [s for s, d in tickers.items() if s.endswith("USDT") and d['volume'] >= GLOBAL_MIN_VOLUME]
                    eligible.sort(key=lambda s: tickers[s]['volume'], reverse=True)
                    current_pairs = eligible[:GLOBAL_MAX_PAIRS]
                    logger.info(f"Global Scan: Found {len(current_pairs)} active pairs")
                else:
                    current_pairs = TRADING_PAIRS
            except Exception as e:
                logger.warning(f"Could not fetch market context: {e}")
                current_pairs = TRADING_PAIRS

            if not current_pairs:
                logger.warning("No pairs to scan. Waiting...")
                await asyncio.sleep(CHECK_INTERVAL)
                continue

            logger.info(f"Scanning {len(current_pairs)} pairs...")
            tasks = [process_pair(client, bot, pair, tickers) for pair in current_pairs]
            await asyncio.gather(*tasks)
            
            logger.info(f"Scan complete. Sleeping {CHECK_INTERVAL}s...")
            await asyncio.sleep(CHECK_INTERVAL)
    except KeyboardInterrupt:
        logger.info("Shutting down...")
    finally:
        await client.close_connection()


if __name__ == "__main__":
    asyncio.run(main())
