"""
strategy.py — AUTO-GENERATED by Signal Bot Constructor
Strategy: {{STRATEGY_NAME}}
Generated: {{GENERATED_AT}}

⚠️  Do not edit this file manually unless you know what you are doing.
    To change strategy logic, use the visual constructor and regenerate.
"""

from indicators import (
    sma, ema, rsi, macd, bollinger_bands, stochastic,
    cross_above, cross_below, avg_volume,
    detect_fvg, detect_order_blocks, detect_market_structure,
    detect_liquidity_sweeps, is_ict_killzone, pump_dump,
    detect_eqh_eql,
    detect_daily_bias, detect_po3, calculate_premium_discount,
    get_scanner_data, get_input_data,
)

# ─── Strategy: {{STRATEGY_NAME}} ───────────────────────────────────────────────
# Signal type: {{SIGNAL_TYPE}}
# Timeframe:   {{TIMEFRAME}}

{{STRATEGY_BODY}}
