import { create } from 'zustand';

export type Language = 'ru' | 'en';

const translations: Record<Language, Record<string, string>> = {
  ru: {
    control_center: "Панель управления",
    canvas_builder: "Конструктор (Канвас)",
    strategy_templates: "Шаблоны стратегий",
    signals_log: "Журнал сигналов",
    paper_trading: "Paper Trading",
    backtest: "Бэктест",
    bot_farm: "Ферма ботов",
    ml_trainer: "ML Trainer (AI)",
    cross_exchange: "Кросс-Биржа (Спреды)",
    documentation: "Документация",
    api_settings: "Настройки API",
    learning_guide: "Обучение (Гид)",
    
    trading_hub: "Торговый Хаб",
    strategy_studio: "Студия Стратегий",
    intelligence_lab: "Лаборатория ИИ",
    fleet_management: "Управление Ботами",
    
    system_healthy: "Система в норме",
    system_degraded: "Неполадки системы",
    loading: "Загрузка...",
    system_status: "Статус системы",
    
    notifications: "Уведомления",
    mark_all_read: "Прочитать все",
    clear_all: "Очистить",
    no_notifications: "Нет новых уведомлений",
    
    light_theme: "Светлая тема",
    dark_theme: "Темная тема",
    
    validate: "Проверить",
    save: "Сохранить",
    optimize: "Оптимизация",
    debug: "Отладка",
    tools: "Инструменты",
    activate: "Активировать",
    deactivate: "Деактивировать",
    import_pine: "Импорт PineScript",
    templates: "Шаблоны",
    auto_layout: "Выровнять ноды",
    version_history: "История версий",
    settings: "Настройки",
    search_pair: "Пара...",
    watchlist: "Watchlist",
    recommended_desktop: "Рекомендуется десктоп",
    mobile_warning: "Визуальный редактор стратегий оптимизирован для широких экранов. На мобильном доступно ограниченное управление.",
    no_connection: "Нет соединения",
    information: "Информация",
    node_help_placeholder: "Выберите ноду на холсте, чтобы настроить её параметры и прочитать документацию.",
    modules_active: "модулей активно",
    validation_passed: "Проверка пройдена ✓",
    validation_error: "Ошибка валидации",
    validation_tooltip: "Проверить логику стратегии",
    genetic_tooltip: "Генетическая оптимизация параметров",
    debug_tooltip: "Режим отладки",
    debug_on: "Отладка: ВКЛ (нажмите чтобы выключить)",
    node_parameters: "Параметры ноды",
    delete_node: "Удалить ноду",
    api_keys_optional: "🔑 API Ключи (необязательно)",
    api_keys_desc: "Без ключей используются публичные данные. С ключами — доступны приватные endpoint'ы (баланс, ордера).",
    api_key_placeholder: "Вставьте API Key...",
    secret_key_placeholder: "Вставьте Secret Key...",
    dashboard_subtitle: "Панель мониторинга активности торговых стратегий и ИИ-сигналов",
    active_strategies: "Активные стратегии",
    docker_pool_utilization: "утилизация пула Docker",
    signals_today: "Сигналы сегодня",
    signals_week: "За неделю",
    signals_7d: "сигналов за 7 дней",
    signals_last_hour: "Последний час",
    signals_in_feed: "новых сигналов в ленте",
    active_signals: "Активность сигналов",
    cumulative_pnl_30d: "Кумулятивный PnL форвард-тестов (30 дней)",
    signals_7d_count: "Кол-во сигналов за последние 7 дней",
    no_trades: "Нет сделок",
    quick_actions: "Быстрые действия",
    create_strategy: "Создать стратегию",
    open_builder: "Открыть конструктор",
    run_backtest: "Запустить бэктест",
    test_history: "Протестировать на истории",
    ready_configs: "Готовые конфигурации",
    integration_settings: "Настройки интеграций",
    integration_sub: "heym, Hermes, Telegram",
    latest_signals: "Последние сигналы",
    all_signals: "Все →",
    system_status_waiting: "SYSTEM STATUS: AWAITING_STREAM",
    passive_waiting_desc: "Запущен пассивный режим ожидания сигналов от Exchange Node.",
    to_launch_flow: "Чтобы запустить активный поток рыночных данных:",
    step_1: "1. Перейдите в Конструктор Канваса.",
    step_2: "2. Создайте новую торговую стратегию на холсте.",
    step_3: "3. Подключите Exchange Connector к блокам RSI/SMC и Trade Action.",
    step_4: "4. Запустите стратегию в один клик.",
    all_systems_ok: "● Все системы ОК",
    there_are_problems: "○ Есть проблемы",
    loading_status: "◌ Загрузка...",
    status_modules: "📊 Статус системных модулей",
    model_learning_feed: "Этот сигнал был сгенерирован по стандартному техническому алгоритму без подключения ИИ-агентов Hermes/LDR.",
    confidence: "Confidence",
    reasoning: "Reasoning:",

    // Sidebar titles and categories
    node_library: "Библиотека нод",
    unpin_panel: "Открепить (скрывать панель)",
    pin_panel: "Закрепить панель",
    "Входные": "Входные",
    "🔌 Биржи": "🔌 Биржи",
    "Индикаторы": "Индикаторы",
    "Smart Money": "Smart Money",
    "📊 Order Flow": "📊 Order Flow",
    "🧠 AI Прогноз": "🧠 AI Прогноз",
    "📈 Статистика": "📈 Статистика",
    "Логика": "Логика",
    "Фильтры": "Фильтры",
    "Выходные": "Выходные",
    "🚀 Торговля": "🚀 Торговля",

    // Block names
    input_mark_price: "Mark Price",
    input_open_interest: "Open Interest",
    input_funding_rate: "Funding Rate",
    scanner_volume24h: "24h Объем",
    scanner_change24h: "24h Изменение %",
    user_level: "Пользовательский Уровень",
    input_webhook: "Внешний Webhook",
    polymarket_scanner: "🔮 Киты Polymarket",
    finviz_scanner: "📈 Finviz Сканнер Акций",
    deribit_pcr: "📊 Deribit Put-Call Ratio",
    exch_universal: "🔌 Коннектор Биржи",
    indicator_rsi: "RSI",
    indicator_divergence: "Дивергенция",
    indicator_sma: "SMA",
    indicator_ema: "EMA",
    indicator_macd: "MACD",
    indicator_bb: "Линии Боллинджера",
    indicator_atr: "ATR",
    indicator_stoch: "Стохастик",
    indicator_volume: "Объем торгов",
    smc_fvg: "Fair Value Gap",
    smc_ob: "Order Block",
    smc_sweep: "Liquidity Sweep",
    smc_ms: "Структура рынка (BOS/CHoCH)",
    smc_bias: "Дневное Направление",
    smc_po3: "Сила трех (PO3)",
    smc_pd: "Премиум/Дисконт",
    smc_killzone: "Киллизона ICT",
    of_delta: "Дельта Объема",
    of_cvd: "CVD (Кумулятивная)",
    of_liq: "Ликвидации",
    of_wall: "Стена в стакане",
    ai_direction: "AI Направление",
    ai_price: "AI Цена",
    sentiment_score: "Настроение рынка",
    ml_predictor: "ML Фильтр",
    hermes_agent: "Агент Hermes",
    heym_mcp: "⚡ heym Валидатор",
    mcp_tool: "🛠️ Вызов MCP Tool",
    mcp_workflow_id: "ID Воркфлоу MCP (Workflow ID)",
    mcp_input_data: "Входные параметры (JSON)",
    mcp_output_key: "Ключ вывода (JSON Output Key)",
    mcp_tool_desc: "🛠️ MCP Tool Call — выполняет произвольный инструмент Model Context Protocol (MCP) через воркфлоу платформы heym.<br/><br/>Позволяет передать любые параметры в формате JSON и получить отфильтрованное решение или конкретное значение.",
    stats_vwap: "VWAP",
    stats_zscore: "Z-Score",
    stats_adr: "ADR Истощение",
    logic_and: "И (AND)",
    logic_or: "ИЛИ (OR)",
    logic_corr: "Фильтр Корреляции",
    comp_cross_above: "Пересечение Снизу Вверх",
    comp_cross_below: "Пересечение Сверху Вниз",
    comp_gt_lt: "> / < Сравнение",
    custom_script: "Свой Скрипт",
    fusion_combiner: "🎛️ Комбинатор Fusion",
    filter_killzone: "Временной Фильтр",
    filter_mtf: "MTF Анализ",
    deep_research: "🔬 Глубокое Исследование",
    portfolio_risk_sizer: "⚖️ Управление Риском",
    signal_long: "LONG Сигнал",
    signal_short: "SHORT Сигнал",
    trade_market_order: "Рыночный Ордер",
    trade_limit_order: "Лимитный Ордер",
    trade_sltp: "Стоп Лосс / Тейк Профит",
    trade_risk: "Защита Риска",
    trade_webhook: "Вебхук Сделки",
    trade_grid: "Сеточный Бот",

    // Custom nodes headers & subtitles
    user_chart_level: "Уровень с графика",
    binding: "Привязка:",
    last_level: "Последний уровень",
    time_filter: "Фильтр времени",
    signal: "Сигнал",
    market_scanner: "Сканер рынка",
    vs_top50_avg_vol: "vs Топ-50 средний объем",
    binance_data: "Данные Binance",
    movement: "Движение:",
    volume: "Объём:",
    candles: "свечи",
    all_markets: "Все рынки",
    min_volume: "Мин. объем:",
    market: "Рынок:",
    metric: "Метрика",
    side: "Сторона",
    threshold: "Порог",
    indicator: "Индикатор",
    mtf_analysis: "MTF АНАЛИЗ",
    higher_tf: "Старший ТФ",
    timeframe_label: "Таймфрейм:",
    mode_label: "Режим:",
    backtest_strategy: "Бэктест стратегии",
    start_date: "Дата начала",
    end_date: "Дата конца",
    initial_balance: "Начальный баланс ($)",
    commission_pct: "Комиссия (%)",
    slippage_pct: "Slippage (%)",
    latency_ms: "Latency (ms)",
    algorithm: "Алгоритм",
    trailing_stop: "Trailing Stop",
    distance_pct: "Дистанция (%)",
    activation_pct: "Активация (%)",
    run_backtest_btn: "Запустить бэктест",
    executing: "Выполнение...",
    import_pine_script: "Импорт Pine Script",
    import_pine_desc: "Вставьте код вашего индикатора (v5). Бот проанализирует условия и автоматически создаст ноды.",
    convert_to_nodes: "Конвертировать в ноды",
    execution_settings: "Настройки запуска",
    enable_live_execution: "Включить реальное исполнение (Live)",
    execution_algo: "Алгоритм исполнения",
    position_size_usd: "Объем позиции (USD)",
    algo_slices_count: "Количество срезов (Slices)",
    algo_duration_mins: "Длительность (минут)",
    vwap_lookback_days: "Глубина VWAP (дней)",
    take_profit_pct: "Take Profit (%)",
    stop_loss_pct: "Stop Loss (%)",
    paper_trading_desc: "Симуляция торговли на демо-балансе",
    trade_risk_management: "Риск-менеджмент сделки",
    save_settings: "Сохранить настройки",
    forward_testing_paper: "Форвард-тестирование (Paper)",
    knowledge_base: "База знаний",
    select_section: "Выберите раздел для чтения...",
    help_title: "Справка: ",
    node_reference: "Справочник нод",
    more_nodes_suffix: "нод в полном мануале...",
    and_more: "И еще",
    open_full_manual: "Открыть полный мануал",
    direction: "Направление",
    auto_from_signal: "Авто (Из сигнала)",
    order_volume: "Объём ордера",
    offset: "Отступ (Offset)",
    max_drawdown_label: "Макс. просадка (DD)",
    max_risk_trade: "Макс. риск на сделку",
    lower_price: "Нижняя цена",
    upper_price: "Верхняя цена",
    grid_levels: "Кол-во уровней",
    grid_type: "Тип сетки",
    arithmetic: "Арифметическая (фиксированный шаг)",
    geometric: "Геометрическая (% шаг)",
    investment_volume: "Объём инвестиций",
    configuration: "Конфигурация",
    inputs_count: "Количество входов",
    how_it_works: "Логика работы:",
    zoom_in: "Увеличить",
    // Cross-Exchange
    cross_exchange_intel: "Кросс-Биржа Intelligence",
    cross_exchange_desc: "Мониторинг арбитражных окон и ценовых расхождений между Binance, Bybit и OKX",
    last_sync: "Последняя синхронизация",
    ref_binance_futures: "Эталон: Binance Futures",
    live_ticker: "В ЭФИРЕ",
    spread_high_warn: "Обнаружено значительное расхождение.",
    spread_synced: "Цены синхронизированы.",
    exploit_spread: "ИСПОЛЬЗОВАТЬ СПРЕД",
    collecting_exchange_data: "Сбор данных с бирж в реальном времени...",
    average_spread: "Средний спред",
    low_volatility: "Низкая волатильность",
    arb_opportunities_24h: "Арбитражные окна (24ч)",
    total_profit_potential: "Потенциал прибыли: 0.8%",
    active_exchanges: "Активные биржи",
    // Signals Log
    signals_all: "Все",
    signals_all_pairs: "Все пары",
    signals_all_strategies: "Все стратегии",
    no_active_signals: "Нет активных сигналов",
    ai_agent: "🧠 AI Агент",
    sent_to_telegram: "Отправлено в Telegram",
    activity_today: "Активность за сегодня",
    strategies_efficiency: "Эффективность стратегий",
    no_closed_trades: "Нет закрытых сделок",
    on_air: "В эфире",
    // Strategy Templates & Catalog Buttons
    active: "Активных",
    total: "Всего",
    signals_today_count: "сигналов сегодня",
    import_json: "Импортировать JSON",
    new_strategy: "Новая стратегия",
    search_placeholder: "Поиск по названию или паре...",
    strategies_active: "Активные",
    strategies_inactive: "Выключены",
    loading_strategies: "Загрузка стратегий...",
    strategies_not_found: "Стратегий не найдено",
    try_change_filters: "Попробуйте изменить фильтры или создать новую стратегию",
    last_7_days: "7 дней",
    delete_strategy_title: "Удалить стратегию?",
    delete_confirm_desc: "Вы собираетесь удалить {name}. Это действие необратимо.",
    cancel: "Отмена",
    delete: "Удалить",
    bot_generator: "Генератор торгового бота",
    preview_code: "Предпросмотр кода",
    strategy_is_valid: "Стратегия валидна",
    strategy_has_errors: "Есть ошибки в стратегии",
    nodes_connected: "Нод: {total} · Подключено: {connected}",
    codegen_error: "Ошибка генерации",
    bot_ready_deploy: "Бот готов к развертыванию",
    run_one_click: "# Запуск в один клик:",
    download_zip: "Скачать исходный код (.zip)",
    process_name: "Имя процесса",
    trading_pairs_label: "Торговые пары",
    timeframe_label_cg: "Таймфрейм",
    check_interval: "Проверка (сек)",
    close: "Закрыть",
    generating: "Генерация...",
    fix_errors: "Исправьте ошибки",
    create_bot_files: "Создать файлы бота",
    simulation_params: "Параметры симуляции",
    backtest_results_title: "Результаты бэктеста",
    final_balance: "Итоговый баланс",
    trades_label: "Сделки",
    // Fleet / Bot Farm
    fleet_management_title: "Централизованное управление флотом торговых ботов",
    panic_stop: "АВАРИЙНАЯ ОСТАНОВКА",
    launch_bot: "+ ЗАПУСТИТЬ БОТА",
    total_pnl: "Общий P&L",
    active_instances: "Активные боты",
    risk_level: "Уровень риска",
    correlation_matrix_1h: "Матрица корреляции (1ч)",
    pair: "Пара",
    balance: "Баланс",
    pnl: "PnL",
    active_position_lbl: "АКТИВНАЯ ПОЗИЦИЯ: ",
    no_active_position: "Нет активной позиции",
    stop: "СТОП",
    start: "СТАРТ",
    logs: "ЛОГИ",
    launch_new_bot: "Запуск нового бота",
    bot_name_placeholder: "Название бота",
    select_strategy: "Выберите стратегию",
    pair_placeholder: "Пара (BTCUSDT)",
    deposit_placeholder: "Депозит ($)",
    // Node Properties Panel (Canvas right section)
    default_option: "По умолчанию",
    data_source: "Источник данных",
    opt_mark_price: "Mark Price (Цена)",
    opt_market_avg_volume: "Avg Volume (Top-50 рынка)",
    opt_candle_close: "Candle Close",
    opt_candle_open: "Candle Open",
    opt_candle_volume: "Candle Volume",
    comparison_condition: "Условие сравнения",
    opt_none_series: "Нет (передать серию)",
    eg_funding: "Напр: 0.005",
    eg_oi: "Напр: 1000000",
    value_label: "Значение",
    custom_pair_opt: "Чужая пара (опционально)",
    eg_pair_default: "Напр: ETHUSDT (текущая по умолч.)",
    custom_pair_desc: "Оставьте пустым — используется пара стратегии. Укажите пару — межрыночный анализ.",
    indicator_label: "Индикатор",
    period_label: "Период",
    model_label_prop: "Модель",
    opt_auto_gpu: "Авто (лучшая под GPU)",
    forecast_horizon: "Горизонт прогноза (свечей)",
    opt_12_candles: "12 свечей",
    opt_24_candles: "24 свечи",
    opt_48_candles: "48 свечей",
    opt_120_candles: "120 свечей",
    output_value: "Выходное значение",
    opt_direction_up_down: "Направление (UP/DOWN)",
    opt_predicted_price: "Прогноз цены",
    opt_predicted_change: "Изменение %",
    opt_confidence_range: "Уверенность (0-1)",
    min_confidence: "Мин. уверенность",
    l2_metric: "Метрика L2",
    opt_spread_diff: "Spread (Разница)",
    analysis_depth_levels: "Глубина анализа (уровней)",
    metric_label: "Метрика",
    opt_vol_usdt: "Объем торгов (USDT)",
    opt_rel_vol: "Относительный объем (vs Топ-50)",
    opt_price_change_pct: "Изменение цены (%)",
    rel_vol_desc: "Сравнивает объем монеты со средним объемом Топ-50 пар. Порог 2.0 = объем вдвое выше среднего.",
    opt_15m: "15 минут",
    opt_1h: "1 час",
    opt_4h: "4 часа",
    opt_24h: "24 часа",
    rel_vol_24h_only: "Относительный объем доступен только за 24ч",
    condition_label: "Условие",
    opt_value_output: "Вывод значения",
    placeholder_multiplier: "Множитель (1.5 = 1.5x)",
    placeholder_value: "Значение",
    start_time_label: "Время начала",
    end_time_label: "Время окончания",
    timezone_label: "Часовой пояс",
    opt_utc_binance: "UTC (Binance сервер)",
    opt_moscow_utc: "Москва (UTC+3)",
    opt_ny_utc: "Нью-Йорк (UTC-5)",
    opt_london_utc: "Лондон (UTC+0/+1)",
    opt_tokyo_utc: "Токио (UTC+9)",
    killzone_recom_desc: "💡 Рекомендуемые сессии: Лондон 07:00–10:00, Нью-Йорк 13:30–16:00, перекрытие 13:00–17:00 UTC",
    cross_direction: "Направление пересечения",
    btn_up: "↗ Вверх",
    btn_down: "↘ Вниз",
    cross_above_desc: "Сигнал: A пересекает B снизу вверх (cross above)",
    cross_below_desc: "Сигнал: A пересекает B сверху вниз (cross below)",
    operator_label: "Оператор",
    value_b_label: "Значение B (если порт B не подключён)",
    placeholder_eg_30: "Напр: 30 (RSI < 30)",
    value_b_desc: "Если порт \"B\" не подключен, будет использоваться это значение.",
    comp_pair_label: "Пара для сравнения",
    min_corr_label: "Мин. корреляция",
    corr_filter_desc: "💡 Бот проверит, насколько сильно эта пара «ходит» вместе с основной. Сигнал пройдет только при высокой связи.",
    opt_volume_delta_curr: "Volume Delta (Текущая свеча)",
    opt_cvd_cumulative: "CVD (Накопительная дельта)",
    opt_1m: "1 минута",
    opt_5m: "5 минут",
    opt_1d: "1 день",
    min_short: "мин",
    liq_side_label: "Сторона ликвидаций",
    opt_long_liq: "LONG (Ликвидации лонгов)",
    opt_short_liq: "SHORT (Ликвидации шортов)",
    opt_both_liq: "BOTH (Все вместе)",
    threshold_usd: "Порог (USD)",
    placeholder_eg_1pct: "Напр. 1%",
    placeholder_eg_3pct: "Напр. 3%",
    liq_large_threshold_desc: "Учитывать только ликвидации крупнее {amount}M",
    liq_desc: "Ликвидации показывают \"боль\" других трейдеров.",
    delta_desc: "Дельта показывает разницу между рыночными покупками и продажами.",
    script_name_label: "Название скрипта",
    eg_script_name: "Напр: RSI Divergence Fix",
    js_code_label: "JavaScript Код",
    js_placeholder: "// Доступные переменные: close, high, low, volume (массивы)\n// Пример: return close[0] > high[1];",
    js_desc: "💡 Вы можете использовать стандартные массивы данных. Индекс 0 — текущая свеча.",
    ml_model_label: "ML Модель",
    select_model_placeholder: "Выберите модель...",
    min_accuracy_label: "Мин. точность: {score}",
    ml_confidence_desc: "💡 Сигнал пройдет только если модель уверена в нем более чем на {pct}%.",
    smc_type_label: "Тип SMC",
    history_depth_label: "Глубина истории (свечей)",
    block_type_label: "Тип блока",
    opt_bullish_buys: "Bullish (Покупки)",
    opt_bearish_sells: "Bearish (Продажи)",
    sweep_type_label: "Тип свипа",
    opt_low_sweep: "Low Sweep (Сбор лонгов)",
    opt_high_sweep: "High Sweep (Сбор шортов)",
    trading_session_label: "Торговая сессия",
    opt_london_session: "Лондон (07:00-10:00)",
    opt_new_york_session: "Нью-Йорк (13:30-16:00)",
    opt_tokyo_session: "Токио (00:00-03:00)",
    opt_sydney_session: "Сидней (21:00-00:00)",
    price_level_label: "Уровень цены ($)",
    placeholder_eg_60k: "Напр: 60000",
    tolerance_label: "Отклонение (%)",
    placeholder_eg_0_1: "Напр: 0.1",
    user_level_desc: "💡 Сигнал срабатывает, когда текущая цена находится в пределах заданного отклонения (Tolerance %) от указанного ценового уровня. Level ID используется для привязки к линиям, нарисованным на графике.",
    opt_aggregator_all: "Агрегатор (Все источники)",
    property_label: "Свойство",
    sentiment_desc: "💡 Используйте этот узел как фильтр. Например: Sentiment Score > 0.3 для подтверждения лонга.",
    min_bet_label: "Минимальная ставка ($)",
    market_slug_label: "Код рынка (Slug - опционально)",
    polymarket_scanner_desc: "💡 Бот в реальном времени отслеживает ставки китов на платформе предсказаний Polymarket. Срабатывает при обнаружении сделок, превышающих лимит.",
    signal_filter_label: "Сигнал / Фильтр",
    opt_top_gainers: "📈 Лидеры роста (Top Gainers)",
    opt_top_losers: "📉 Лидеры падения (Top Losers)",
    opt_new_high: "🚀 Новые максимумы (New High)",
    opt_new_low: "🩸 Новые минимумы (New Low)",
    opt_most_volatile: "⚡ Высокая волатильность (Most Volatile)",
    opt_most_active: "🔥 Наиболее активные (Most Active)",
    opt_overbought: "⚠️ Перекупленность (RSI > 70)",
    opt_oversold: "🟢 Перепроданность (RSI < 30)",
    opt_insider_buying: "💎 Покупки инсайдеров (CEO/CFO Buys)",
    opt_insider_selling: "🚪 Продажи инсайдеров (Insider Sales)",
    min_daily_volume_label: "Мин. дневной объем",
    opt_amount_shares: "{amount} акций",
    min_stock_price_label: "Минимальная цена акции ($)",
    finviz_scanner_desc: "💡 Сканирует фондовый рынок США в реальном времени. Возвращает список тикеров, удовлетворяющих критерию, для передачи торговым нодам или AI-анализаторам.",
    insider_deals_option_label: "Тип сделок инсайдеров",
    insider_option_latest: "Последние сделки (все)",
    insider_option_top: "Крупные сделки директоров (Киты)",
    short_float_filter_label: "Фильтр Short Float (Процент шортов)",
    sma_200_filter_label: "Технический фильтр SMA 200",
    inst_own_filter_label: "Участие институционалов (%)",
    opt_any: "Любой (Без фильтра)",
    opt_high_15: "Высокий (>15%)",
    opt_very_high_25: "Очень высокий (>25%)",
    opt_inst_high_50: "Высокое (>50%)",
    opt_inst_very_high_70: "Доминирующее (>70%)",
    opt_above_sma200: "Цена выше SMA200 (Бычий)",
    opt_below_sma200: "Цена ниже SMA200 (Медвежий)",
    analysis_timeframe_label: "Таймфрейм для анализа",
    analysis_mode_label: "Режим анализа",
    mtf_desc: "📈 MTF (Multi-Timeframe) Анализ: Позволяет оценивать индикаторы или логические условия на таймфрейме, отличном от глобального таймфрейма стратегии.\n\nПример использования:\nПоместите индикатор RSI внутрь MTF-блока с таймфреймом 4H, чтобы входить в сделки по глобальному таймфрейму 15m только тогда, когда старший тренд (4H) находится в перепроданности.",
    search_query_label: "Поисковый запрос",
    pair_placeholder_desc: "Используйте {{pair}} — будет заменено на активную торговую пару",
    research_mode_label: "Режим исследования",
    output_signal_type_label: "Тип выходного сигнала",
    block_risk_level_label: "Блокировать при уровне риска ≥",
    opt_risk_medium: "Medium (средний и выше)",
    opt_risk_high: "High (высокий и выше)",
    opt_risk_critical: "Critical (только критический)",
    results_cache_mins: "Кэш результатов (мин.)",
    cache_zero_desc: "0 = без кэша (каждый раз новый запрос к LDR)",
    deep_research_desc: "🔬 Local Deep Research (LDR) — автономный ИИ-агент анализирует новости, регуляторные события, взломы и рыночные катализаторы.\n\nРежимы выхода:\n• Risk Filter — пропускает сделку если риск ниже порога\n• Sentiment Score — числовой (-1.0 → +1.0) для Fusion Combiner\n• Block Critical — блокирует только при критических событиях",
    base_trade_size: "Базовый объем сделки (USD)",
    risk_mgmt_model: "Модель риск-менеджмента",
    opt_equal_risk: "Equal Risk (Постоянный объем)",
    opt_atr_adaptive: "ATR Adaptive (Динамическая волатильность)",
    correlation_threshold_label: "Порог корреляции с открытыми позициями",
    correlation_threshold_desc: "Снижает объем позиции при корреляции returns выше этого порога",
    atr_period_candles: "Период ATR (свечи)",
    portfolio_risk_sizer_desc: "⚖️ Portfolio Risk Sizer — рассчитывает оптимальный объем позиции.\n\n• ATR Adaptive: Снижает размер ордера при высокой волатильности, сохраняя риск в долларах постоянным.\n\n• Correlation Control: Автоматически находит открытые виртуальные позиции, рассчитывает коэффициент Пирсона для returns за последние 50 свечей и пропорционально уменьшает объем при росте рыночной концентрации.",
    ai_mode_label: "Режим ИИ",
    min_confidence_level: "Минимальный уровень уверенности",
    llm_model_name: "Имя модели LLM",
    historical_testing: "Тестирование на исторических данных",
    use_mock_backtest: "Использовать Mock в Бэктестах",
    use_mock_backtest_limits: "Использовать Mock в Бэктестах (не тратит лимиты API)",
    ai_prompt_template: "Шаблон промпта для ИИ",
    ai_prompt_placeholders_desc: "Доступные плейсхолдеры: {{placeholders}}",
    hermes_desc: "🧠 Hermes AI Agent — когнитивный фильтр сигналов.\n\nПромпт динамически обогащается индикаторами и отправляется на выбранный LLM эндпоинт. В бэктестах решение подменяется эмуляцией при включенной галочке.",
    validation_mode_label: "Режим валидации",
    additional_ai_context: "Дополнительный контекст для ИИ",
    eg_additional_context: "Например: 'Увеличивай риск при росте объема рынка на >20%'",
    heym_validator_desc: "⚡ heym Validator — выполняет интеллектуальную фильтрацию торговых сигналов с помощью автономного ИИ-воркфлоу на платформе heym.\n\nРежимы:\n• Filter: Жесткий пропуск сделки на базе бинарного решения ИИ.\n• Score: Сравнение рейтинга уверенности от ИИ с вашим порогом.",
    deribit_pcr_desc: "💡 Deribit PCR (Put-Call Ratio): Индикатор настроения опционного рынка.\n\nПоказывает соотношение объемов опционов Put (ставка на падение) к Call (ставка на рост).\n\n• PCR > 1.0: Преобладают путы (медвежий сентимент опционов).\n• PCR < 0.7: Преобладают коллы (сильный бычий сентимент опционов).",
    inputs_count_label: "Количество входов",
    trigger_threshold: "Порог срабатывания",
    indicator_weights: "Веса индикаторов",
    input_prefix: "Вход",
    self_learning_weights: "Самообучение весов (Learning Engine)",
    enable_online_adaptation: "Включить онлайн-адаптацию весов",
    learning_rate_alpha: "Скорость обучения (Alpha)",
    alpha_ema_desc: "💡 Alpha (EMA): Определяет, насколько сильно результаты последних 24 часов влияют на изменение весов.",
    exchange_label: "Биржа",
    data_type_label: "Тип данных",
    opt_price_curr: "Price (Текущая цена)",
    opt_vol_24h: "Volume 24h (Объём)",
    opt_funding_rate_f: "Funding Rate (Фандинг)",
    opt_open_interest_oi: "Open Interest (Откр. интерес)",
    opt_price_delta_arb: "⚡ Price Delta (арбитраж)",
    pair_ticker_label: "Тикер пары",
    eg_ticker: "Напр. BTCUSDT, BTC/USD",
    compare_with_second: "Сравнивать с (вторая биржа)",
    price_delta_desc: "💡 Price Delta = (price_B − price_A) / price_A × 100%. Сигнал когда дельта превышает порог.",
    funding_rate_warn_desc: "💡 Фандинг > 0.01% — перегрев лонгов. Фандинг < −0.01% — перегрев шортов.",
    connect_comparison_desc: "💡 Подключите выход к Comparison или Логике для дальнейшей фильтрации.",
    top_coins_label: "Топ монет",
    symbols_filter_label: "Символы (фильтр)",
    eg_symbols: "Напр. BTCUSDT, ETHUSDT",
    symbols_filter_desc: "Оставьте пустым для сканирования всего рынка. Укажите через запятую для мульти-символьного фильтра.",
    sorting_label: "Сортировка",
    opt_by_vol: "По объёму",
    opt_by_change: "По изменению",
    opt_by_price: "По цене",
    filters_header: "Фильтры",
    no_limits_label: "Без ограничений",
    scanner_return_desc: "💡 Сканер возвращает список монет удовлетворяющих фильтрам. Подключите к другим нодам для применения стратегии к каждой монете.",
    api_keys_optional_header: "🔑 API Ключи (необязательно)",
    api_keys_desc_label: "Без ключей используются публичные данные. С ключами — доступны приватные endpoint'ы (баланс, ордера).",
    api_keys_warning_desc: "⚠️ Ключи хранятся только в данной стратегии. Используйте read-only ключи без прав на вывод.",
    operation_mode_label: "Режим работы",
    opt_mode_ticker: "📈 Тикер (Конкретная пара)",
    opt_mode_scanner: "🔍 Сканер рынка (Мульти-поиск)",
    opt_mode_orderbook: "📊 Анализ стакана (Order Book L2)",
    opt_mode_orderflow: "⚡ Поток ордеров (CVD & Delta)",
    opt_by_vol_24h: "По объёму 24ч (Volume ↓)",
    opt_by_change_up: "▲ Лидеры роста (Gainers)",
    opt_by_change_down: "▼ Лидеры падения (Losers)",
    opt_imbalance_bid_ask: "Imbalance % (Дисбаланс объемов бид/аск)",
    opt_spread_size: "Spread size (Ширина спреда)",
    opt_wall_distance_large: "Wall Distance (Дистанция до крупных заявок)",
    levels_count_label: "Кол-во уровней",
    opt_delta_net_diff: "Delta (Чистая разница рыночных покупок/продаж)",
    opt_cvd_cumulative_vol: "CVD (Кумулятивная дельта объемов)",
    calculation_period_label: "Период расчета",
    opt_side_both: "Обе стороны (LONG & SHORT)",
    opt_side_long: "Только покупки (LONG)",
    opt_side_short: "Только продажи (SHORT)",
    min_vol_threshold_usd: "Минимальный порог объема ($)",
    http_method_label: "HTTP Метод",
    grid_lower_boundary: "Нижняя граница сетки",
    grid_upper_boundary: "Верхняя граница сетки",
    webhook_url_label: "URL Webhook",
    eg_volume_or_usd: "Напр. 100% или 500 USDT",
    eg_offset_or_usd: "Напр. -0.5% или -10 USDT",
    eg_1pct: "Напр. 1%",
    eg_3pct: "Напр. 3%",
    eg_5pct: "Напр. 5%",
    eg_20pct: "Напр. 20%",
    eg_investment_volume: "Напр. 50% или 1000 USDT",
    current_price_label: "Текущая цена",
    quote_asset_label: "Quote asset",
    min_price_label: "Min Price ($)",
    max_price_label: "Max Price ($)",
    min_change_label: "Min Change 24h (%)",
    max_change_label: "Max Change 24h (%)",
    side_label: "Сторона",
    // Inline & Node Body Parameters
    node_params_header: "Параметры",
    node_timeframe_label: "Таймфрейм",
    node_timeframe_default: "По умолчанию",
    node_indicator_label: "Индикатор",
    node_source_label: "Источник",
    node_condition_label: "Условие",
    node_value_label: "Значение",
    node_stream_option: "Поток",
    node_operator_label: "Оператор",
    node_direction_label: "Направление",
    node_direction_above: "↗ Вверх",
    node_direction_below: "↘ Вниз",
    node_inputs_label: "Входов",
    node_inputs_abbr: "вх.",
    node_signal_type: "Тип сигнала",
    node_session_label: "Сессия",
    node_from_label: "С",
    node_to_label: "По",
    node_metric_label: "Метрика",
    node_period_label: "Период",
    node_model_label: "Модель",
    node_horizon_label: "Горизонт",
    node_output_label: "Выход",
    node_levels_label: "Уровней",
    node_side_label: "Сторона",
    node_threshold_usd: "Порог ($)",
    node_price_movement_pct: "Движение %",
    node_vol_multiplier: "Vol multiplier",
    node_lookback: "Lookback",
    node_aggregator: "Агрегатор",
    node_property: "Свойство",
    node_loading: "⏳ Загрузка…",
    node_select_model: "— Выбрать модель —",
    node_no_trained_models: "Нет обученных моделей. Перейдите в ML Trainer.",
    node_mode_label: "Режим",
    node_cache_mins: "Кэш (мин)",
    node_prompt_label: "Промпт:",
    node_price_label: "Цена",
    node_tolerance_pct: "Откл. %",
    node_name_label: "Имя",
    node_exchange_params: "Параметры Биржи",
    node_exchange_label: "Биржа",
    node_data_type: "Тип данных",
    node_pair_label: "Пара",
    node_compare_exchange: "VS Биржа",
    node_quote_asset: "Квота",
    node_symbols_label: "Символы",
    node_top_n: "Топ N",
    node_sorting_label: "Сортировка",
    node_filters_optional: "Фильтры (необяз.)",
    node_min_vol: "Min Vol ($)",
    node_max_vol: "Max Vol ($)",
    node_min_chg: "Min Chg%",
    node_max_chg: "Max Chg%",
    node_min_price: "Min Price",
    node_max_price: "Max Price",
    node_volume_label: "Объём",
    node_offset_label: "Отступ",
    node_stop_loss: "Stop Loss",
    node_take_profit: "Take Profit",
    node_lower_price: "Low",
    node_upper_price: "High",
    node_grids_count: "Grids",
    node_grid_type: "Тип",
    node_ttl_sec: "TTL (сек)",
    node_field_label: "Поле",
    node_expected_value: "Значение",
    node_any_payload: "Any payload",
    node_match_field: "Match field",
    node_multi_timeframe: "Multi-Timeframe",
    node_input_node: "Входной",
    node_comparison_node: "Сравнение",
    node_cross_node: "Пересечение",
    node_crosses_above: "пересекает вверх",
    node_crosses_below: "пересекает вниз",
    node_options_tf: "Таймфрейм опционов:",
    node_data_type_lbl: "Тип данных:",
    node_oi_volumes: "Объемы Open Interest (Put/Call)",
    node_api_keys_configured: "API ключи настроены",
    node_no_filters_all: "Нет фильтров — все монеты",
    node_weighted_fusion: "Взвешенное слияние",
    node_threshold: "Порог",
    node_learning_ema: "Обучение (EMA)",
    node_status_active: "АКТИВНО",
    node_status_off: "ВЫКЛ",
    node_parameter: "Параметр:",
    node_instrument: "Инструмент:",
    node_compare_with: "Сравнить с:",
    node_instruments: "Инструменты:",
    node_order_book_metric: "Метрика стакана:",
    node_levels_depth: "Глубина уровней:",
    node_order_flow: "Поток ордеров:",
    node_period_side: "Период & Сторона:",
    node_volume_threshold: "Порог объема:",
    node_finviz_gainers: "Лидеры роста (Gainers)",
    node_finviz_losers: "Лидеры падения (Losers)",
    node_finviz_highs: "Новые максимумы (Highs)",
    node_finviz_lows: "Новые минимумы (Lows)",
    node_finviz_volatile: "Высокая волатильность",
    node_finviz_active: "Наиболее активные",
    node_finviz_overbought: "Перекупленность (RSI > 70)",
    node_finviz_oversold: "Перепроданность (RSI < 30)",
    node_finviz_insider_buy: "Крупные покупки инсайдеров",
    node_finviz_insider_sell: "Крупные продажи инсайдеров",
    node_finviz_signal: "Сигнал:",
    node_finviz_min_vol: "Мин. Объем:",
    node_finviz_min_price: "Мин. Цена:",
    opt_risk_filter: "Фильтр рисков (risk_filter)",
    opt_sentiment_score: "Оценка настроений (sentiment_score)",
    opt_block_critical: "Блокировать только критические",
    opt_score_confidence: "Score (Рейтинг уверенности)",
    opt_filter_pass_block: "Filter (PASS / BLOCK)",
    placeholder_tolerance_eg: "Напр. 0.1",
    level_id_chart_link: "ID уровня (Связь с графиком)",

    // LLM Filter (Free AI)
    llm_filter: "🤖 LLM Фильтр (Free AI)",
    llm_filter_provider_label: "Провайдер LLM",
    llm_filter_model_label: "Модель",
    llm_filter_prompt_label: "Промпт для анализа",
    llm_filter_temperature_label: "Температура (0-1)",
    llm_filter_mock_backtest: "Мок в бэктесте (PASS/FILTER без LLM)",
    llm_filter_prompt_vars: "Доступные переменные: {{pair}}, {{price}}, {{rsi}}, {{trend}}, {{volume}}, {{timeframe}}",
    llm_filter_desc: "🤖 LLM Фильтр (Free AI) — фильтрует сигналы через бесплатный веб-интерфейс Qwen/DeepSeek с помощью Playwright.\n\n⚠️ ВАЖНО (Авторизация): Требуется активная сессия в браузере. Выполните логин через Playwright интерактивно (non-headless) или скопируйте cookies сессии в директорию .free-ai/ внутри Docker-контейнера для сохранения состояния авторизации.\n\nВ бэктесте: автоматически подменяется моком.",
    opt_provider_qwen: "Qwen (chat.qwen.ai)",
    opt_provider_deepseek: "DeepSeek (chat.deepseek.com)",
    opt_model_qwen_max: "qwen-max (быстрый)",
    opt_model_qwen_plus: "qwen-plus (расширенный)",
    opt_model_deepseek_reasoner: "deepseek-reasoner (Think)",
    opt_model_deepseek_chat: "deepseek-chat (быстрый)",
  },
  en: {
    control_center: "Control Center",
    canvas_builder: "Canvas Builder",
    strategy_templates: "Strategy Templates",
    signals_log: "Signals Log",
    paper_trading: "Paper Trading",
    backtest: "Backtest",
    bot_farm: "Bot Farm",
    ml_trainer: "ML Trainer (AI)",
    cross_exchange: "Cross-Exchange",
    documentation: "Documentation",
    api_settings: "API Settings",
    learning_guide: "Learning Guide",
    
    trading_hub: "Trading Hub",
    strategy_studio: "Strategy Studio",
    intelligence_lab: "Intelligence Lab",
    fleet_management: "Fleet Management",
    
    system_healthy: "System Healthy",
    system_degraded: "System Degraded",
    loading: "Loading...",
    system_status: "System Status",
    
    notifications: "Notifications",
    mark_all_read: "Mark all read",
    clear_all: "Clear all",
    no_notifications: "No new notifications",
    
    light_theme: "Light Theme",
    dark_theme: "Dark Theme",
    
    validate: "Validate",
    save: "Save",
    optimize: "Optimize",
    debug: "Debug",
    tools: "Tools",
    activate: "Activate",
    deactivate: "Deactivate",
    import_pine: "Import PineScript",
    templates: "Templates",
    auto_layout: "Auto Layout",
    version_history: "Version History",
    settings: "Settings",
    search_pair: "Pair...",
    watchlist: "Watchlist",
    recommended_desktop: "Desktop Recommended",
    mobile_warning: "The visual strategy builder is optimized for wide screens. Limited controls are available on mobile.",
    no_connection: "No connection",
    information: "Information",
    node_help_placeholder: "Select a node on the canvas to configure its parameters and read documentation.",
    modules_active: "modules active",
    validation_passed: "Validation passed ✓",
    validation_error: "Validation error",
    validation_tooltip: "Validate strategy logic",
    genetic_tooltip: "Genetic parameter optimization",
    debug_tooltip: "Debug mode",
    debug_on: "Debug: ON (click to disable)",
    node_parameters: "Node Parameters",
    delete_node: "Delete Node",
    api_keys_optional: "🔑 API Keys (optional)",
    api_keys_desc: "Without keys, public data is used. With keys, private endpoints (balance, orders) are available.",
    api_key_placeholder: "Insert API Key...",
    secret_key_placeholder: "Insert Secret Key...",
    dashboard_subtitle: "Monitoring dashboard for trading strategies and AI signals",
    active_strategies: "Active Strategies",
    docker_pool_utilization: "Docker pool utilization",
    signals_today: "Signals Today",
    signals_week: "This Week",
    signals_7d: "signals in 7 days",
    signals_last_hour: "Last Hour",
    signals_in_feed: "new signals in feed",
    active_signals: "Signal Activity",
    cumulative_pnl_30d: "Cumulative PnL forward-tests (30 days)",
    signals_7d_count: "Signals count over last 7 days",
    no_trades: "No trades",
    quick_actions: "Quick Actions",
    create_strategy: "Create Strategy",
    open_builder: "Open Canvas Builder",
    run_backtest: "Run Backtest",
    test_history: "Test on historical data",
    ready_configs: "Ready-made configurations",
    integration_settings: "Integration Settings",
    integration_sub: "heym, Hermes, Telegram",
    latest_signals: "Latest Signals",
    all_signals: "All →",
    system_status_waiting: "SYSTEM STATUS: AWAITING_STREAM",
    passive_waiting_desc: "Passive mode waiting for signals from Exchange Node is running.",
    to_launch_flow: "To start active market data stream:",
    step_1: "1. Go to Canvas Builder.",
    step_2: "2. Create a new trading strategy on canvas.",
    step_3: "3. Connect Exchange Connector to RSI/SMC and Trade Action blocks.",
    step_4: "4. Activate strategy in one click.",
    all_systems_ok: "● All systems OK",
    there_are_problems: "○ System degraded",
    loading_status: "◌ Loading...",
    status_modules: "📊 System Modules Status",
    model_learning_feed: "This signal was generated by standard technical algorithm without Hermes/LDR AI agents.",
    confidence: "Confidence",
    reasoning: "Reasoning:",

    // Sidebar titles and categories
    node_library: "Node Library",
    unpin_panel: "Unpin (hide panel)",
    pin_panel: "Pin panel",
    "Входные": "Inputs",
    "🔌 Биржи": "🔌 Exchanges",
    "Индикаторы": "Indicators",
    "Smart Money": "Smart Money",
    "📊 Order Flow": "📊 Order Flow",
    "🧠 AI Прогноз": "🧠 AI Forecast",
    "📈 Статистика": "📈 Stats",
    "Логика": "Logic",
    "Фильтры": "Filters",
    "Выходные": "Outputs",
    "🚀 Торговля": "🚀 Trading",

    // Block names
    input_mark_price: "Mark Price",
    input_open_interest: "Open Interest",
    input_funding_rate: "Funding Rate",
    scanner_volume24h: "24h Volume",
    scanner_change24h: "24h Change %",
    user_level: "User Chart Level",
    input_webhook: "External Webhook",
    polymarket_scanner: "🔮 Polymarket Whales",
    finviz_scanner: "📈 Finviz Stock Scanner",
    deribit_pcr: "📊 Deribit Put-Call Ratio",
    exch_universal: "🔌 Exchange Connector",
    indicator_rsi: "RSI",
    indicator_divergence: "Divergence",
    indicator_sma: "SMA",
    indicator_ema: "EMA",
    indicator_macd: "MACD",
    indicator_bb: "Bollinger Bands",
    indicator_atr: "ATR",
    indicator_stoch: "Stochastic",
    indicator_volume: "Volume",
    smc_fvg: "Fair Value Gap",
    smc_ob: "Order Block",
    smc_sweep: "Liquidity Sweep",
    smc_ms: "Market Structure",
    smc_bias: "Daily Bias",
    smc_po3: "Power of 3",
    smc_pd: "Premium/Discount",
    smc_killzone: "ICT Killzone",
    of_delta: "Volume Delta",
    of_cvd: "CVD (Cumulative)",
    of_liq: "Liquidations",
    of_wall: "Orderbook Wall",
    ai_direction: "AI Forecast",
    ai_price: "AI Price",
    sentiment_score: "Market Sentiment",
    ml_predictor: "ML Predictor",
    hermes_agent: "Hermes Agent",
    heym_mcp: "⚡ heym Validator",
    mcp_tool: "🛠️ MCP Tool Call",
    mcp_workflow_id: "MCP Workflow ID",
    mcp_input_data: "Input parameters (JSON)",
    mcp_output_key: "JSON Output Key",
    mcp_tool_desc: "🛠️ MCP Tool Call — executes any custom Model Context Protocol (MCP) tool via heym workflow automation.<br/><br/>Allows passing arbitrary parameters in JSON format and retrieves filtered decisions or raw output values.",
    stats_vwap: "VWAP",
    stats_zscore: "Z-Score",
    stats_adr: "ADR Exhaustion",
    logic_and: "AND",
    logic_or: "OR",
    logic_corr: "Correlation Filter",
    comp_cross_above: "Cross Above",
    comp_cross_below: "Cross Below",
    comp_gt_lt: "> / <",
    custom_script: "Custom Script",
    fusion_combiner: "🎛️ Fusion Combiner",
    filter_killzone: "Killzone",
    filter_mtf: "MTF Analysis",
    deep_research: "🔬 Deep Research (LDR)",
    portfolio_risk_sizer: "⚖️ Portfolio Risk Sizer",
    signal_long: "LONG Signal",
    signal_short: "SHORT Signal",
    trade_market_order: "Market Order",
    trade_limit_order: "Limit Order",
    trade_sltp: "SL / TP",
    trade_risk: "Risk Guard",
    trade_webhook: "Webhook",
    trade_grid: "Grid Bot",

    // Custom nodes headers & subtitles
    user_chart_level: "User Chart Level",
    binding: "Binding:",
    last_level: "Last level",
    time_filter: "Time Filter",
    signal: "Signal",
    market_scanner: "Market Scanner",
    vs_top50_avg_vol: "vs Top-50 avg volume",
    binance_data: "Binance Data",
    movement: "Movement:",
    volume: "Volume:",
    candles: "candles",
    all_markets: "All Markets",
    min_volume: "Min. volume:",
    market: "Market:",
    metric: "Metric",
    side: "Side",
    threshold: "Threshold",
    indicator: "Indicator",
    mtf_analysis: "MTF Analysis",
    higher_tf: "Higher TF",
    timeframe_label: "Timeframe:",
    mode_label: "Mode:",
    backtest_strategy: "Backtest Strategy",
    start_date: "Start Date",
    end_date: "End Date",
    initial_balance: "Initial Balance ($)",
    commission_pct: "Commission (%)",
    slippage_pct: "Slippage (%)",
    latency_ms: "Latency (ms)",
    algorithm: "Algorithm",
    trailing_stop: "Trailing Stop",
    distance_pct: "Distance (%)",
    activation_pct: "Activation (%)",
    run_backtest_btn: "Run Backtest",
    executing: "Executing...",
    import_pine_script: "Import Pine Script",
    import_pine_desc: "Paste your indicator code (v5). The bot will analyze conditions and automatically create nodes.",
    convert_to_nodes: "Convert to Nodes",
    execution_settings: "Launch Settings",
    enable_live_execution: "Enable Live Execution",
    execution_algo: "Execution Algorithm",
    position_size_usd: "Position Size (USD)",
    algo_slices_count: "Algo Slices Count",
    algo_duration_mins: "Algo Duration (Minutes)",
    vwap_lookback_days: "VWAP Lookback (Days)",
    take_profit_pct: "Take Profit (%)",
    stop_loss_pct: "Stop Loss (%)",
    paper_trading_desc: "Trading simulation on demo balance",
    trade_risk_management: "Trade Risk Management",
    save_settings: "Save Settings",
    forward_testing_paper: "Forward-Testing (Paper)",
    knowledge_base: "Knowledge Base",
    select_section: "Select a section to read...",
    help_title: "Help: ",
    node_reference: "Node Reference",
    more_nodes_suffix: "nodes in the full manual...",
    and_more: "And",
    open_full_manual: "Open Full Manual",
    direction: "Direction",
    auto_from_signal: "Auto (From signal)",
    order_volume: "Order Volume",
    offset: "Offset",
    max_drawdown_label: "Max Drawdown (DD)",
    max_risk_trade: "Max Risk per Trade",
    lower_price: "Lower Price",
    upper_price: "Upper Price",
    grid_levels: "Grid Levels",
    grid_type: "Grid Type",
    arithmetic: "Arithmetic (Fixed step)",
    geometric: "Geometric (% step)",
    investment_volume: "Investment Volume",
    configuration: "Configuration",
    inputs_count: "Number of inputs",
    how_it_works: "How it works:",
    zoom_in: "Zoom",
    // Cross-Exchange
    cross_exchange_intel: "Cross-Exchange Intelligence",
    cross_exchange_desc: "Monitoring of arbitrage windows and price deltas between Binance, Bybit and OKX",
    last_sync: "Last Sync",
    ref_binance_futures: "Reference: Binance Futures",
    live_ticker: "LIVE",
    spread_high_warn: "Significant spread detected.",
    spread_synced: "Prices are synchronized.",
    exploit_spread: "EXPLOIT SPREAD",
    collecting_exchange_data: "Collecting exchange data in real time...",
    average_spread: "Average Spread",
    low_volatility: "Low Volatility",
    arb_opportunities_24h: "Arb Opportunities (24h)",
    total_profit_potential: "Total Profit Potential: 0.8%",
    active_exchanges: "Active Exchanges",
    // Signals Log
    signals_all: "All",
    signals_all_pairs: "All pairs",
    signals_all_strategies: "All strategies",
    no_active_signals: "No active signals",
    ai_agent: "🤖 AI Agent",
    sent_to_telegram: "Sent to Telegram",
    activity_today: "Activity today",
    strategies_efficiency: "Strategies efficiency",
    no_closed_trades: "No closed trades",
    on_air: "Live",
    // Strategy Templates & Catalog Buttons
    active: "Active",
    total: "Total",
    signals_today_count: "signals today",
    import_json: "Import JSON",
    new_strategy: "New Strategy",
    search_placeholder: "Search by name or pair...",
    strategies_active: "Active",
    strategies_inactive: "Inactive",
    loading_strategies: "Loading strategies...",
    strategies_not_found: "No strategies found",
    try_change_filters: "Try changing filters or create a new strategy",
    last_7_days: "7 days",
    delete_strategy_title: "Delete strategy?",
    delete_confirm_desc: "You are about to delete {name}. This action is irreversible.",
    cancel: "Cancel",
    delete: "Delete",
    bot_generator: "Bot Generator",
    preview_code: "Preview Code",
    strategy_is_valid: "Strategy is valid",
    strategy_has_errors: "Strategy has errors",
    nodes_connected: "Nodes: {total} · Connected: {connected}",
    codegen_error: "Generation error",
    bot_ready_deploy: "Bot ready to deploy",
    run_one_click: "# Launch in one click:",
    download_zip: "Download Source Code (.zip)",
    process_name: "Process Name",
    trading_pairs_label: "Trading Pairs",
    timeframe_label_cg: "Timeframe",
    check_interval: "Check (sec)",
    close: "Close",
    generating: "Generating...",
    fix_errors: "Fix errors",
    create_bot_files: "Create bot files",
    simulation_params: "Simulation Parameters",
    backtest_results_title: "Backtest Results",
    final_balance: "Final Balance",
    trades_label: "Trades",
    // Fleet / Bot Farm
    fleet_management_title: "Centralized Management of Trading Bots Fleet",
    panic_stop: "PANIC STOP",
    launch_bot: "+ LAUNCH BOT",
    total_pnl: "Total P&L",
    active_instances: "Active Instances",
    risk_level: "Risk Level",
    correlation_matrix_1h: "Correlation Matrix (1h)",
    pair: "Pair",
    balance: "Balance",
    pnl: "PnL",
    active_position_lbl: "ACTIVE POSITION: ",
    no_active_position: "No active position",
    stop: "STOP",
    start: "START",
    logs: "LOGS",
    launch_new_bot: "Launch New Bot",
    bot_name_placeholder: "Bot Name",
    select_strategy: "Select Strategy",
    pair_placeholder: "Pair (BTCUSDT)",
    deposit_placeholder: "Deposit ($)",
    // Node Properties Panel (Canvas right section)
    default_option: "Default",
    data_source: "Data Source",
    opt_mark_price: "Mark Price",
    opt_market_avg_volume: "Avg Volume (Top-50 market)",
    opt_candle_close: "Candle Close",
    opt_candle_open: "Candle Open",
    opt_candle_volume: "Candle Volume",
    comparison_condition: "Comparison Condition",
    opt_none_series: "None (pass series)",
    eg_funding: "e.g. 0.005",
    eg_oi: "e.g. 1000000",
    value_label: "Value",
    custom_pair_opt: "Custom Pair (optional)",
    eg_pair_default: "e.g. ETHUSDT (default current)",
    custom_pair_desc: "Leave empty to use strategy pair. Specify a pair for cross-market analysis.",
    indicator_label: "Indicator",
    period_label: "Period",
    model_label_prop: "Model",
    opt_auto_gpu: "Auto (best for GPU)",
    forecast_horizon: "Forecast Horizon (candles)",
    opt_12_candles: "12 candles",
    opt_24_candles: "24 candles",
    opt_48_candles: "48 candles",
    opt_120_candles: "120 candles",
    output_value: "Output Value",
    opt_direction_up_down: "Direction (UP/DOWN)",
    opt_predicted_price: "Predicted Price",
    opt_predicted_change: "Change %",
    opt_confidence_range: "Confidence (0-1)",
    min_confidence: "Min Confidence",
    l2_metric: "L2 Metric",
    opt_spread_diff: "Spread (Difference)",
    analysis_depth_levels: "Analysis Depth (levels)",
    metric_label: "Metric",
    opt_vol_usdt: "Trading Volume (USDT)",
    opt_rel_vol: "Relative Volume (vs Top-50)",
    opt_price_change_pct: "Price Change (%)",
    rel_vol_desc: "Compares coin volume to average Top-50 volume. Threshold 2.0 = double the average.",
    opt_15m: "15 minutes",
    opt_1h: "1 hour",
    opt_4h: "4 hours",
    opt_24h: "24 hours",
    rel_vol_24h_only: "Relative volume only available for 24h",
    condition_label: "Condition",
    opt_value_output: "Value Output",
    placeholder_multiplier: "Multiplier (1.5 = 1.5x)",
    placeholder_value: "Value",
    start_time_label: "Start Time",
    end_time_label: "End Time",
    timezone_label: "Timezone",
    opt_utc_binance: "UTC (Binance server)",
    opt_moscow_utc: "Moscow (UTC+3)",
    opt_ny_utc: "New York (UTC-5)",
    opt_london_utc: "London (UTC+0/+1)",
    opt_tokyo_utc: "Tokyo (UTC+9)",
    killzone_recom_desc: "💡 Recommended sessions: London 07:00–10:00, New York 13:30–16:00, overlap 13:00–17:00 UTC",
    cross_direction: "Cross Direction",
    btn_up: "↗ Up",
    btn_down: "↘ Down",
    cross_above_desc: "Signal: A crosses B from bottom to top (cross above)",
    cross_below_desc: "Signal: A crosses B from top to bottom (cross below)",
    operator_label: "Operator",
    value_b_label: "Value B (if port B is disconnected)",
    placeholder_eg_30: "e.g. 30 (RSI < 30)",
    value_b_desc: "If port \"B\" is not connected, this value will be used.",
    comp_pair_label: "Comparison Pair",
    min_corr_label: "Min Correlation",
    corr_filter_desc: "💡 The bot will check how closely this pair moves with the primary one. Signal will only pass if correlation is high.",
    opt_volume_delta_curr: "Volume Delta (Current candle)",
    opt_cvd_cumulative: "CVD (Cumulative delta)",
    opt_1m: "1 minute",
    opt_5m: "5 minutes",
    opt_1d: "1 day",
    min_short: "min",
    liq_side_label: "Liquidation Side",
    opt_long_liq: "LONG (Long liquidations)",
    opt_short_liq: "SHORT (Short liquidations)",
    opt_both_liq: "BOTH (All together)",
    threshold_usd: "Threshold (USD)",
    placeholder_eg_1pct: "e.g. 1%",
    placeholder_eg_3pct: "e.g. 3%",
    liq_large_threshold_desc: "Only consider liquidations larger than {amount}M",
    liq_desc: "Liquidations show the \"pain\" of other traders.",
    delta_desc: "Delta shows the net difference between market buy and sell orders.",
    script_name_label: "Script Name",
    eg_script_name: "e.g. RSI Divergence Fix",
    js_code_label: "JavaScript Code",
    js_placeholder: "// Available variables: close, high, low, volume (arrays)\n// Example: return close[0] > high[1];",
    js_desc: "💡 You can use standard data arrays. Index 0 is the current candle.",
    ml_model_label: "ML Model",
    select_model_placeholder: "Select model...",
    min_accuracy_label: "Min Accuracy: {score}",
    ml_confidence_desc: "💡 The signal will only pass if the model is confident in it by more than {pct}%.",
    smc_type_label: "SMC Type",
    history_depth_label: "History Depth (candles)",
    block_type_label: "Block Type",
    opt_bullish_buys: "Bullish (Buys)",
    opt_bearish_sells: "Bearish (Sells)",
    sweep_type_label: "Sweep Type",
    opt_low_sweep: "Low Sweep (Long stop run)",
    opt_high_sweep: "High Sweep (Short stop run)",
    trading_session_label: "Trading Session",
    opt_london_session: "London (07:00-10:00)",
    opt_new_york_session: "New York (13:30-16:00)",
    opt_tokyo_session: "Tokyo (00:00-03:00)",
    opt_sydney_session: "Sydney (21:00-00:00)",
    price_level_label: "Price Level ($)",
    placeholder_eg_60k: "e.g. 60000",
    tolerance_label: "Tolerance (%)",
    placeholder_eg_0_1: "e.g. 0.1",
    user_level_desc: "💡 The signal triggers when the current price is within the set deviation (Tolerance %) from the specified price level. Level ID is used for binding to lines drawn on the chart.",
    opt_aggregator_all: "Aggregator (All sources)",
    property_label: "Property",
    sentiment_desc: "💡 Use this node as a filter. For example: Sentiment Score > 0.3 to confirm long.",
    min_bet_label: "Minimum Bet ($)",
    market_slug_label: "Market Slug (optional)",
    polymarket_scanner_desc: "💡 The bot tracks whale bets on prediction platform Polymarket in real time. Triggers when transactions exceeding the limit are detected.",
    signal_filter_label: "Signal / Filter",
    opt_top_gainers: "Top Gainers",
    opt_top_losers: "Top Losers",
    opt_new_high: "New Highs",
    opt_new_low: "New Lows",
    opt_most_volatile: "Most Volatile",
    opt_most_active: "Most Active",
    opt_overbought: "Overbought (RSI > 70)",
    opt_oversold: "Oversold (RSI < 30)",
    opt_insider_buying: "Insider Buying (CEO/CFO Buys)",
    opt_insider_selling: "Insider Selling (Insider Sales)",
    min_daily_volume_label: "Min Daily Volume",
    opt_amount_shares: "{amount} shares",
    min_stock_price_label: "Minimum Stock Price ($)",
    finviz_scanner_desc: "💡 Scans the US stock market in real time. Returns a list of tickers matching the criteria to pass to trading nodes or AI analyzers.",
    insider_deals_option_label: "Insider Deals Type",
    insider_option_latest: "Latest Transactions (all)",
    insider_option_top: "Top Director Deals (Whales)",
    short_float_filter_label: "Short Float % Filter",
    sma_200_filter_label: "SMA 200 Technical Filter",
    inst_own_filter_label: "Institutional Ownership (%)",
    opt_any: "Any (No filter)",
    opt_high_15: "High (>15%)",
    opt_very_high_25: "Very High (>25%)",
    opt_inst_high_50: "High (>50%)",
    opt_inst_very_high_70: "Dominating (>70%)",
    opt_above_sma200: "Price above SMA200 (Bullish)",
    opt_below_sma200: "Price below SMA200 (Bearish)",
    analysis_timeframe_label: "Analysis Timeframe",
    analysis_mode_label: "Analysis Mode",
    mtf_desc: "📈 MTF (Multi-Timeframe) Analysis: Allows evaluating indicators or logical conditions on a timeframe different from the global strategy timeframe.\n\nUsage Example:\nPlace the RSI indicator inside the MTF block with a 4H timeframe, so that entries on the global 15m timeframe only occur when the higher-timeframe trend (4H) is oversold.",
    search_query_label: "Search Query",
    pair_placeholder_desc: "Use {{pair}} — will be replaced with the active trading pair",
    research_mode_label: "Research Mode",
    output_signal_type_label: "Output Signal Type",
    block_risk_level_label: "Block at Risk Level ≥",
    opt_risk_medium: "Medium (medium & above)",
    opt_risk_high: "High (high & above)",
    opt_risk_critical: "Critical (critical only)",
    results_cache_mins: "Results Cache (min)",
    cache_zero_desc: "0 = no cache (always fetch new query from LDR)",
    deep_research_desc: "🔬 Local Deep Research (LDR) — autonomous AI agent analyzes news, regulatory events, hacks and market catalysts.\n\nOutput Modes:\n• Risk Filter — lets trade pass if risk is below threshold\n• Sentiment Score — numeric (-1.0 → +1.0) for Fusion Combiner\n• Block Critical — blocks only on critical events",
    base_trade_size: "Base Trade Size (USD)",
    risk_mgmt_model: "Risk Management Model",
    opt_equal_risk: "Equal Risk (Constant size)",
    opt_atr_adaptive: "ATR Adaptive (Dynamic volatility)",
    correlation_threshold_label: "Correlation Threshold with Open Positions",
    correlation_threshold_desc: "Reduces position size when returns correlation is above this threshold",
    atr_period_candles: "ATR Period (candles)",
    portfolio_risk_sizer_desc: "⚖️ Portfolio Risk Sizer — calculates optimal position size.\n\n• ATR Adaptive: Reduces order size during high volatility, keeping dollar risk constant.\n\n• Correlation Control: Automatically scans open virtual positions, calculates Pearson coefficient for returns over the last 50 candles, and proportionally reduces volume when market concentration increases.",
    ai_mode_label: "AI Mode",
    min_confidence_level: "Minimum Confidence Level",
    llm_model_name: "LLM Model Name",
    historical_testing: "Historical Data Testing",
    use_mock_backtest: "Use Mock in Backtests",
    use_mock_backtest_limits: "Use Mock in Backtests (doesn't spend API limits)",
    ai_prompt_template: "AI Prompt Template",
    ai_prompt_placeholders_desc: "Available placeholders: {{placeholders}}",
    hermes_desc: "🧠 Hermes AI Agent — cognitive signal filter.\n\nPrompt is dynamically enriched with indicators and sent to selected LLM endpoint. In backtests, decisions are replaced with emulation if checked.",
    validation_mode_label: "Validation Mode",
    additional_ai_context: "Additional Context for AI",
    eg_additional_context: "e.g. 'Increase risk when market volume grows by >20%'",
    heym_validator_desc: "⚡ heym Validator — performs intelligent trade signal filtering using an autonomous AI workflow on the heym platform.\n\nModes:\n• Filter: Hard trade bypass based on AI binary decision.\n• Score: Compare AI confidence rating with your threshold.",
    deribit_pcr_desc: "💡 Deribit Put-Call Ratio (PCR): Option market sentiment indicator.\n\nShows volume ratio of Put options (bearish bet) to Call options (bullish bet).\n\n• PCR > 1.0: Puts dominate (bearish options sentiment).\n• PCR < 0.7: Calls dominate (strong bullish options sentiment).",
    inputs_count_label: "Number of Inputs",
    trigger_threshold: "Trigger Threshold",
    indicator_weights: "Indicator Weights",
    input_prefix: "Input",
    self_learning_weights: "Self-Learning Weights (Learning Engine)",
    enable_online_adaptation: "Enable online weight adaptation",
    learning_rate_alpha: "Learning Rate (Alpha)",
    alpha_ema_desc: "💡 Alpha (EMA): Determines how much the last 24 hours of results affect weight adjustments.",
    exchange_label: "Exchange",
    data_type_label: "Data Type",
    opt_price_curr: "Price (Current price)",
    opt_vol_24h: "Volume 24h (Volume)",
    opt_funding_rate_f: "Funding Rate",
    opt_open_interest_oi: "Open Interest",
    opt_price_delta_arb: "⚡ Price Delta (arbitrage)",
    pair_ticker_label: "Pair Ticker",
    eg_ticker: "e.g. BTCUSDT, BTC/USD",
    compare_with_second: "Compare with (second exchange)",
    price_delta_desc: "💡 Price Delta = (price_B − price_A) / price_A × 100%. Signal when delta exceeds threshold.",
    funding_rate_warn_desc: "💡 Funding Rate > 0.01% — longs overleveraged. Funding Rate < −0.01% — shorts overleveraged.",
    connect_comparison_desc: "💡 Connect output to Comparison or Logic for further filtering.",
    top_coins_label: "Top Coins",
    symbols_filter_label: "Symbols (filter)",
    eg_symbols: "e.g. BTCUSDT, ETHUSDT",
    symbols_filter_desc: "Leave empty to scan entire market. Comma-separated for multi-symbol filter.",
    sorting_label: "Sorting",
    opt_by_vol: "By volume",
    opt_by_change: "By change",
    opt_by_price: "By price",
    filters_header: "Filters",
    no_limits_label: "No limits",
    scanner_return_desc: "💡 Scanner returns list of coins matching filters. Connect to other nodes to apply strategy to each coin.",
    api_keys_optional_header: "🔑 API Keys (optional)",
    api_keys_desc_label: "Without keys, public data is used. With keys, private endpoints (balance, orders) are available.",
    api_keys_warning_desc: "⚠️ Keys are stored only within this strategy. Use read-only keys with no withdrawal permissions.",
    operation_mode_label: "Operation Mode",
    opt_mode_ticker: "📈 Ticker (Specific pair)",
    opt_mode_scanner: "🔍 Market Scanner (Multi-search)",
    opt_mode_orderbook: "📊 Order Book Analysis (L2)",
    opt_mode_orderflow: "⚡ Order Flow (CVD & Delta)",
    opt_by_vol_24h: "By 24h volume (Volume ↓)",
    opt_by_change_up: "▲ Top Gainers",
    opt_by_change_down: "▼ Top Losers",
    opt_imbalance_bid_ask: "Imbalance % (Bid/Ask volume imbalance)",
    opt_spread_size: "Spread size",
    opt_wall_distance_large: "Wall Distance (Distance to large orders)",
    levels_count_label: "Levels Count",
    opt_delta_net_diff: "Delta (Net market buy/sell difference)",
    opt_cvd_cumulative_vol: "CVD (Cumulative volume delta)",
    calculation_period_label: "Calculation Period",
    opt_side_both: "Both sides (LONG & SHORT)",
    opt_side_long: "Buys only (LONG)",
    opt_side_short: "Sells only (SHORT)",
    min_vol_threshold_usd: "Minimum Volume Threshold ($)",
    http_method_label: "HTTP Method",
    grid_lower_boundary: "Grid lower boundary",
    grid_upper_boundary: "Grid upper boundary",
    webhook_url_label: "Webhook URL",
    eg_volume_or_usd: "e.g. 100% or 500 USDT",
    eg_offset_or_usd: "e.g. -0.5% or -10 USDT",
    eg_1pct: "e.g. 1%",
    eg_3pct: "e.g. 3%",
    eg_5pct: "e.g. 5%",
    eg_20pct: "e.g. 20%",
    eg_investment_volume: "e.g. 50% or 1000 USDT",
    current_price_label: "Current Price",
    quote_asset_label: "Quote asset",
    min_price_label: "Min Price ($)",
    max_price_label: "Max Price ($)",
    min_change_label: "Min Change 24h (%)",
    max_change_label: "Max Change 24h (%)",
    side_label: "Side",
    // Inline & Node Body Parameters
    node_params_header: "Parameters",
    node_timeframe_label: "Timeframe",
    node_timeframe_default: "Default",
    node_indicator_label: "Indicator",
    node_source_label: "Source",
    node_condition_label: "Condition",
    node_value_label: "Value",
    node_stream_option: "Stream",
    node_operator_label: "Operator",
    node_direction_label: "Direction",
    node_direction_above: "↗ Up",
    node_direction_below: "↘ Down",
    node_inputs_label: "Inputs",
    node_inputs_abbr: "in.",
    node_signal_type: "Signal Type",
    node_session_label: "Session",
    node_from_label: "From",
    node_to_label: "To",
    node_metric_label: "Metric",
    node_period_label: "Period",
    node_model_label: "Model",
    node_horizon_label: "Horizon",
    node_output_label: "Output",
    node_levels_label: "Levels",
    node_side_label: "Side",
    node_threshold_usd: "Threshold ($)",
    node_price_movement_pct: "Movement %",
    node_vol_multiplier: "Vol multiplier",
    node_lookback: "Lookback",
    node_aggregator: "Aggregator",
    node_property: "Property",
    node_loading: "⏳ Loading…",
    node_select_model: "— Select Model —",
    node_no_trained_models: "No trained models. Go to ML Trainer.",
    node_mode_label: "Mode",
    node_cache_mins: "Cache (min)",
    node_prompt_label: "Prompt:",
    node_price_label: "Price",
    node_tolerance_pct: "Tolerance %",
    node_name_label: "Name",
    node_exchange_params: "Exchange Params",
    node_exchange_label: "Exchange",
    node_data_type: "Data Type",
    node_pair_label: "Pair",
    node_compare_exchange: "VS Exchange",
    node_quote_asset: "Quote",
    node_symbols_label: "Symbols",
    node_top_n: "Top N",
    node_sorting_label: "Sorting",
    node_filters_optional: "Filters (optional)",
    node_min_vol: "Min Vol ($)",
    node_max_vol: "Max Vol ($)",
    node_min_chg: "Min Chg%",
    node_max_chg: "Max Chg%",
    node_min_price: "Min Price",
    node_max_price: "Max Price",
    node_volume_label: "Volume",
    node_offset_label: "Offset",
    node_stop_loss: "Stop Loss",
    node_take_profit: "Take Profit",
    node_lower_price: "Low",
    node_upper_price: "High",
    node_grids_count: "Grids",
    node_grid_type: "Type",
    node_ttl_sec: "TTL (sec)",
    node_field_label: "Field",
    node_expected_value: "Value",
    node_any_payload: "Any payload",
    node_match_field: "Match field",
    node_multi_timeframe: "Multi-Timeframe",
    node_input_node: "Input",
    node_comparison_node: "Comparison",
    node_cross_node: "Cross",
    node_crosses_above: "crosses above",
    node_crosses_below: "crosses below",
    node_options_tf: "Options Timeframe:",
    node_data_type_lbl: "Data Type:",
    node_oi_volumes: "Open Interest Volumes (Put/Call)",
    node_api_keys_configured: "API keys configured",
    node_no_filters_all: "No filters — all coins",
    node_weighted_fusion: "Weighted Fusion",
    node_threshold: "Threshold",
    node_learning_ema: "Learning (EMA)",
    node_status_active: "ACTIVE",
    node_status_off: "OFF",
    node_parameter: "Parameter:",
    node_instrument: "Instrument:",
    node_compare_with: "Compare with:",
    node_instruments: "Instruments:",
    node_order_book_metric: "Order Book Metric:",
    node_levels_depth: "Levels Depth:",
    node_order_flow: "Order Flow:",
    node_period_side: "Period & Side:",
    node_volume_threshold: "Volume Threshold:",
    node_finviz_gainers: "Top Gainers (Gainers)",
    node_finviz_losers: "Top Losers (Losers)",
    node_finviz_highs: "New Highs (Highs)",
    node_finviz_lows: "New Lows (Lows)",
    node_finviz_volatile: "Most Volatile",
    node_finviz_active: "Most Active",
    node_finviz_overbought: "Overbought (RSI > 70)",
    node_finviz_oversold: "Oversold (RSI < 30)",
    node_finviz_insider_buy: "Insider Buying (CEO/CFO Buys)",
    node_finviz_insider_sell: "Insider Selling (Insider Sales)",
    node_finviz_signal: "Signal:",
    node_finviz_min_vol: "Min Volume:",
    node_finviz_min_price: "Min Price:",
    opt_risk_filter: "Risk Filter (risk_filter)",
    opt_sentiment_score: "Sentiment Score (sentiment_score)",
    opt_block_critical: "Block Critical Only",
    opt_score_confidence: "Score (Confidence score)",
    opt_filter_pass_block: "Filter (PASS / BLOCK)",
    placeholder_tolerance_eg: "e.g. 0.1",
    level_id_chart_link: "Level ID (Chart link)",

    // LLM Filter (Free AI)
    llm_filter: "🤖 LLM Filter (Free AI)",
    llm_filter_provider_label: "LLM Provider",
    llm_filter_model_label: "Model",
    llm_filter_prompt_label: "Analysis Prompt",
    llm_filter_temperature_label: "Temperature (0-1)",
    llm_filter_mock_backtest: "Mock in backtest (no LLM calls)",
    llm_filter_prompt_vars: "Available variables: {{pair}}, {{price}}, {{rsi}}, {{trend}}, {{volume}}, {{timeframe}}",
    llm_filter_desc: "🤖 LLM Filter (Free AI) — filters signals via Qwen/DeepSeek web interface using Playwright.\n\n⚠️ IMPORTANT (Auth): Requires active browser profile. Authenticate via interactive (non-headless) Playwright session, or copy active session cookies to the .free-ai/ directory inside Docker volume to persist session state.\n\nIn backtest: automatically replaced with a mock.",
    opt_provider_qwen: "Qwen (chat.qwen.ai)",
    opt_provider_deepseek: "DeepSeek (chat.deepseek.com)",
    opt_model_qwen_max: "qwen-max (fast)",
    opt_model_qwen_plus: "qwen-plus (extended)",
    opt_model_deepseek_reasoner: "deepseek-reasoner (Think)",
    opt_model_deepseek_chat: "deepseek-chat (fast)",
  }
};

const detectLanguage = (): Language => {
  const stored = localStorage.getItem('language') as Language;
  if (stored === 'ru' || stored === 'en') return stored;
  
  const systemLang = navigator.language || (navigator.languages && navigator.languages[0]) || '';
  return systemLang.toLowerCase().includes('ru') ? 'ru' : 'en';
};

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: detectLanguage(),
  setLanguage: (lang) => {
    localStorage.setItem('language', lang);
    set({ language: lang });
  },
  t: (key) => {
    const { language } = get();
    return translations[language][key] || translations['en'][key] || key;
  }
}));
